import type {
  AssetBook,
  AssetLifecycleEvent,
  DepreciationScheduleLine,
  FixedAsset,
} from '@/lib/types'

export const fixedAssets: FixedAsset[] = [
  {
    id: 'fa-1001',
    assetNumber: 'FA-1001',
    name: 'Chicago HQ Leasehold Refresh',
    entityId: 'e1',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-close',
    projectName: 'Q1 Close Acceleration',
    category: 'leasehold',
    status: 'in_service',
    capitalizationStatus: 'capitalized',
    acquisitionDate: new Date('2025-12-18'),
    inServiceDate: new Date('2026-01-03'),
    cost: 188000,
    accumulatedDepreciation: 15667,
    netBookValue: 172333,
    salvageValue: 5000,
    usefulLifeMonths: 60,
    depreciationMethod: 'straight_line',
    bookId: 'book-corp-us',
    bookName: 'Corporate Book',
    vendorName: 'Northline Interiors',
    locationName: 'Chicago HQ',
    serialNumber: 'CHI-LL-4401',
    updatedAt: new Date('2026-04-04T08:20:00'),
  },
  {
    id: 'fa-1002',
    assetNumber: 'FA-1002',
    name: 'Denver CNC Router',
    entityId: 'e2',
    departmentId: 'd-ops',
    departmentName: 'Operations',
    category: 'equipment',
    status: 'active',
    capitalizationStatus: 'queued',
    acquisitionDate: new Date('2026-03-20'),
    cost: 265000,
    accumulatedDepreciation: 0,
    netBookValue: 265000,
    salvageValue: 18000,
    usefulLifeMonths: 84,
    depreciationMethod: 'straight_line',
    bookId: 'book-corp-us',
    bookName: 'Corporate Book',
    vendorName: 'Vertex Components',
    locationName: 'Denver Plant',
    serialNumber: 'DEN-CNC-2209',
    updatedAt: new Date('2026-04-04T09:10:00'),
  },
  {
    id: 'fa-1003',
    assetNumber: 'FA-1003',
    name: 'ERP Integration Middleware',
    entityId: 'e1',
    departmentId: 'd-it',
    departmentName: 'IT',
    projectId: 'p-erp',
    projectName: 'ERP Data Migration',
    category: 'software',
    status: 'hold',
    capitalizationStatus: 'needs_review',
    acquisitionDate: new Date('2026-02-11'),
    cost: 142000,
    accumulatedDepreciation: 5900,
    netBookValue: 136100,
    salvageValue: 0,
    usefulLifeMonths: 36,
    depreciationMethod: 'straight_line',
    bookId: 'book-corp-us',
    bookName: 'Corporate Book',
    vendorName: 'CloudRail Systems',
    locationName: 'Chicago HQ',
    serialNumber: 'IT-MW-9810',
    updatedAt: new Date('2026-04-03T15:40:00'),
  },
  {
    id: 'fa-1004',
    assetNumber: 'FA-1004',
    name: 'Berlin Service Fleet Van',
    entityId: 'e3',
    departmentId: 'd-ops',
    departmentName: 'Operations',
    category: 'vehicle',
    status: 'disposed',
    capitalizationStatus: 'capitalized',
    acquisitionDate: new Date('2024-06-14'),
    inServiceDate: new Date('2024-06-20'),
    cost: 42000,
    accumulatedDepreciation: 31150,
    netBookValue: 10850,
    salvageValue: 4000,
    usefulLifeMonths: 48,
    depreciationMethod: 'straight_line',
    bookId: 'book-local-eu',
    bookName: 'EU Local Book',
    vendorName: 'Berliner Fleet GmbH',
    locationName: 'Berlin Office',
    serialNumber: 'EU-VAN-1144',
    updatedAt: new Date('2026-04-01T10:05:00'),
  },
]

export const assetBooks: AssetBook[] = [
  { id: 'book-fa-1', assetId: 'fa-1001', entityId: 'e1', name: 'Corporate Book', bookType: 'corporate', depreciationMethod: 'straight_line', usefulLifeMonths: 60, inServiceDate: new Date('2026-01-03'), costBasis: 188000, accumulatedDepreciation: 15667, netBookValue: 172333, status: 'active' },
  { id: 'book-fa-2', assetId: 'fa-1002', entityId: 'e2', name: 'Corporate Book', bookType: 'corporate', depreciationMethod: 'straight_line', usefulLifeMonths: 84, inServiceDate: new Date('2026-04-15'), costBasis: 265000, accumulatedDepreciation: 0, netBookValue: 265000, status: 'hold' },
  { id: 'book-fa-3', assetId: 'fa-1003', entityId: 'e1', name: 'Corporate Book', bookType: 'corporate', depreciationMethod: 'straight_line', usefulLifeMonths: 36, inServiceDate: new Date('2026-02-12'), costBasis: 142000, accumulatedDepreciation: 5900, netBookValue: 136100, status: 'hold' },
  { id: 'book-fa-4', assetId: 'fa-1004', entityId: 'e3', name: 'EU Local Book', bookType: 'local', depreciationMethod: 'straight_line', usefulLifeMonths: 48, inServiceDate: new Date('2024-06-20'), costBasis: 42000, accumulatedDepreciation: 31150, netBookValue: 10850, status: 'closed' },
]

export const depreciationScheduleLines: DepreciationScheduleLine[] = [
  { id: 'dep-1', assetId: 'fa-1001', assetName: 'Chicago HQ Leasehold Refresh', entityId: 'e1', departmentId: 'd-fin', projectId: 'p-close', periodLabel: 'Apr 2026', scheduledDate: new Date('2026-04-30'), depreciationAmount: 3050, accumulatedDepreciation: 18717, endingBookValue: 169283, status: 'scheduled', bookId: 'book-corp-us', bookName: 'Corporate Book' },
  { id: 'dep-2', assetId: 'fa-1002', assetName: 'Denver CNC Router', entityId: 'e2', departmentId: 'd-ops', periodLabel: 'Apr 2026', scheduledDate: new Date('2026-04-30'), depreciationAmount: 0, accumulatedDepreciation: 0, endingBookValue: 265000, status: 'exception', bookId: 'book-corp-us', bookName: 'Corporate Book' },
  { id: 'dep-3', assetId: 'fa-1003', assetName: 'ERP Integration Middleware', entityId: 'e1', departmentId: 'd-it', projectId: 'p-erp', periodLabel: 'Apr 2026', scheduledDate: new Date('2026-04-30'), depreciationAmount: 3944, accumulatedDepreciation: 9844, endingBookValue: 132156, status: 'exception', bookId: 'book-corp-us', bookName: 'Corporate Book' },
  { id: 'dep-4', assetId: 'fa-1004', assetName: 'Berlin Service Fleet Van', entityId: 'e3', departmentId: 'd-ops', periodLabel: 'Mar 2026', scheduledDate: new Date('2026-03-31'), depreciationAmount: 791, accumulatedDepreciation: 31150, endingBookValue: 10850, status: 'posted', bookId: 'book-local-eu', bookName: 'EU Local Book' },
]

export const assetLifecycleEvents: AssetLifecycleEvent[] = [
  { id: 'fa-event-1', assetId: 'fa-1001', assetName: 'Chicago HQ Leasehold Refresh', entityId: 'e1', eventType: 'capitalized', eventDate: new Date('2026-01-03'), description: 'Placed in service and capitalization memo approved.', status: 'completed', amount: 188000, userName: 'Ava Mitchell' },
  { id: 'fa-event-2', assetId: 'fa-1002', assetName: 'Denver CNC Router', entityId: 'e2', eventType: 'created', eventDate: new Date('2026-03-20'), description: 'Asset record created from receiving workflow.', status: 'pending', amount: 265000, userName: 'Lena Garcia' },
  { id: 'fa-event-3', assetId: 'fa-1002', assetName: 'Denver CNC Router', entityId: 'e2', eventType: 'capitalized', eventDate: new Date('2026-04-04'), description: 'Capitalization blocked until warranty memo is attached.', status: 'exception', amount: 265000, userName: 'Miles Chen' },
  { id: 'fa-event-4', assetId: 'fa-1003', assetName: 'ERP Integration Middleware', entityId: 'e1', eventType: 'reclassed', eventDate: new Date('2026-04-03'), description: 'Classification under review between software and implementation cost.', status: 'exception', amount: 142000, userName: 'Noah Wells' },
  { id: 'fa-event-5', assetId: 'fa-1004', assetName: 'Berlin Service Fleet Van', entityId: 'e3', eventType: 'disposed', eventDate: new Date('2026-04-01'), description: 'Disposed after fleet replacement and local approval.', status: 'completed', amount: 10850, userName: 'Miles Chen' },
]
