import type { Role, RoleHomeConfig, RolePermission, User } from '@/lib/types'

export const roles: Role[] = [
  {
    id: 'accountant',
    name: 'Accountant',
    description: 'Daily operator focused on close, reconciliations, and exceptions.',
    landingRoute: '/',
    navigationModules: ['home', 'work-queue', 'general-ledger', 'cash-management', 'reports'],
    accentLabel: 'Close'
  },
  {
    id: 'ap_specialist',
    name: 'AP Specialist',
    description: 'Manages vendor onboarding, bills, approvals, and disbursements.',
    landingRoute: '/accounts-payable',
    navigationModules: ['accounts-payable', 'work-queue', 'cash-management', 'reports'],
    accentLabel: 'Payables'
  },
  {
    id: 'ar_specialist',
    name: 'AR Specialist',
    description: 'Owns invoicing, collections, receipts, and customer balances.',
    landingRoute: '/accounts-receivable',
    navigationModules: ['accounts-receivable', 'work-queue', 'cash-management', 'reports'],
    accentLabel: 'Receivables'
  },
  {
    id: 'controller',
    name: 'Controller',
    description: 'Oversees close, controls, consolidations, and reporting accuracy.',
    landingRoute: '/general-ledger',
    navigationModules: ['general-ledger', 'reports', 'work-queue', 'admin'],
    accentLabel: 'Controls'
  },
  {
    id: 'cfo',
    name: 'CFO',
    description: 'Reviews performance, trends, consolidation, and forecast readiness.',
    landingRoute: '/reports',
    navigationModules: ['reports', 'cash-management', 'admin'],
    accentLabel: 'Performance'
  },
  {
    id: 'admin',
    name: 'Admin',
    description: 'Administers users, workflows, integrations, and system settings.',
    landingRoute: '/admin/users',
    navigationModules: ['admin', 'reports', 'integrations'],
    accentLabel: 'Platform'
  },
]

export const rolePermissions: RolePermission[] = [
  {
    roleId: 'accountant',
    permissions: [
      'dashboard.view',
      'transactions.view',
      'journal_entries.view',
      'journal_entries.manage',
      'chart_of_accounts.view',
      'close.view',
      'close.manage',
      'reconciliation.view',
      'reconciliation.manage',
      'reports.view',
      'saved_views.manage',
      'search.global',
    ],
  },
  {
    roleId: 'ap_specialist',
    permissions: [
      'dashboard.view',
      'bills.view',
      'bills.manage',
      'transactions.view',
      'saved_views.manage',
      'reports.view',
      'search.global',
    ],
  },
  {
    roleId: 'ar_specialist',
    permissions: [
      'dashboard.view',
      'invoices.view',
      'invoices.manage',
      'transactions.view',
      'saved_views.manage',
      'reports.view',
      'search.global',
    ],
  },
  {
    roleId: 'controller',
    permissions: [
      'dashboard.view',
      'transactions.view',
      'transactions.export',
      'bills.view',
      'invoices.view',
      'journal_entries.view',
      'journal_entries.manage',
      'chart_of_accounts.view',
      'chart_of_accounts.manage',
      'close.view',
      'close.manage',
      'reconciliation.view',
      'reports.view',
      'reports.build',
      'saved_views.manage',
      'search.global',
    ],
  },
  {
    roleId: 'cfo',
    permissions: [
      'dashboard.view',
      'transactions.view',
      'transactions.export',
      'reports.view',
      'reports.build',
      'saved_views.manage',
      'search.global',
    ],
  },
  {
    roleId: 'admin',
    permissions: [
      'dashboard.view',
      'transactions.view',
      'bills.view',
      'invoices.view',
      'journal_entries.view',
      'chart_of_accounts.manage',
      'close.manage',
      'reports.build',
      'saved_views.manage',
      'search.global',
      'admin.manage',
      'integrations.manage',
      'api.manage',
    ],
  },
]

export const roleHomeConfigs: RoleHomeConfig[] = [
  {
    roleId: 'accountant',
    title: 'Accounting Workbench',
    subtitle: 'Today’s close-critical work, exceptions, and reconciliations.',
    primaryModule: 'work-queue',
    defaultRoute: '/',
    emphasis: ['tasks_due_today', 'unreconciled_transactions', 'draft_journals', 'close_progress', 'exceptions'],
    quickActions: [
      { id: 'qa-1', label: 'New Journal Entry', href: '/general-ledger/journal-entries' },
      { id: 'qa-2', label: 'Review Reconciliation', href: '/cash-management/reconciliation' },
      { id: 'qa-3', label: 'Open Work Queue', href: '/work-queue' },
    ],
  },
  {
    roleId: 'ap_specialist',
    title: 'Payables Control Tower',
    subtitle: 'Bills, approvals, and payment readiness by entity.',
    primaryModule: 'accounts-payable',
    defaultRoute: '/accounts-payable',
    emphasis: ['pending_bills', 'approvals', 'discounts'],
    quickActions: [
      { id: 'qa-4', label: 'New Bill', href: '/accounts-payable/bills' },
      { id: 'qa-5', label: 'Vendor Queue', href: '/accounts-payable/vendors' },
    ],
  },
  {
    roleId: 'ar_specialist',
    title: 'Receivables Command Center',
    subtitle: 'Invoice issuance, collections, and receipt application.',
    primaryModule: 'accounts-receivable',
    defaultRoute: '/accounts-receivable',
    emphasis: ['open_invoices', 'collections', 'cash_receipts'],
    quickActions: [
      { id: 'qa-6', label: 'New Invoice', href: '/accounts-receivable/invoices' },
      { id: 'qa-7', label: 'Apply Receipt', href: '/accounts-receivable/receipts' },
    ],
  },
  {
    roleId: 'controller',
    title: 'Controllership Overview',
    subtitle: 'Close progress, policy adherence, and reporting readiness.',
    primaryModule: 'general-ledger',
    defaultRoute: '/general-ledger',
    emphasis: ['close_status', 'trial_balance', 'exceptions'],
    quickActions: [
      { id: 'qa-8', label: 'Trial Balance', href: '/general-ledger/reports/trial-balance' },
      { id: 'qa-9', label: 'Close Tasks', href: '/work-queue' },
    ],
  },
  {
    roleId: 'cfo',
    title: 'Executive Finance Summary',
    subtitle: 'Performance, liquidity, and forecast variance.',
    primaryModule: 'reports',
    defaultRoute: '/reports',
    emphasis: ['kpis', 'trends', 'forecast'],
    quickActions: [{ id: 'qa-10', label: 'Run P&L', href: '/reports/income-statement' }],
  },
  {
    roleId: 'admin',
    title: 'Platform Administration',
    subtitle: 'User access, workflows, integrations, and controls.',
    primaryModule: 'admin',
    defaultRoute: '/admin/users',
    emphasis: ['users', 'integrations', 'workflows'],
    quickActions: [{ id: 'qa-11', label: 'Manage Users', href: '/admin/users' }],
  },
]

export const users: User[] = [
  {
    id: 'u1',
    email: 'ava.mitchell@northstarfinance.com',
    firstName: 'Ava',
    lastName: 'Mitchell',
    displayName: 'Ava Mitchell',
    role: 'accountant',
    status: 'active',
    entityIds: ['e1', 'e2', 'e3', 'e4'],
    primaryEntityId: 'e4',
    title: 'Senior Accountant',
    createdAt: new Date('2024-01-02T09:00:00'),
    lastLoginAt: new Date('2026-04-04T09:12:00'),
    preferences: {
      theme: 'system',
      defaultEntity: 'e4',
      defaultDateRange: 'this_month',
      sidebarCollapsed: false,
      notifications: {
        email: true,
        push: true,
        approvals: true,
        tasks: true,
      },
    },
  },
  {
    id: 'u2',
    email: 'miles.chen@northstarfinance.com',
    firstName: 'Miles',
    lastName: 'Chen',
    displayName: 'Miles Chen',
    role: 'controller',
    status: 'active',
    entityIds: ['e1', 'e2', 'e4'],
    primaryEntityId: 'e1',
    title: 'Controller',
    createdAt: new Date('2023-09-15T09:00:00'),
    lastLoginAt: new Date('2026-04-03T18:20:00'),
  },
  {
    id: 'u3',
    email: 'lena.garcia@northstarfinance.com',
    firstName: 'Lena',
    lastName: 'Garcia',
    displayName: 'Lena Garcia',
    role: 'ap_specialist',
    status: 'active',
    entityIds: ['e1', 'e2'],
    primaryEntityId: 'e1',
    title: 'AP Specialist',
    createdAt: new Date('2024-02-12T09:00:00'),
    lastLoginAt: new Date('2026-04-04T08:30:00'),
  },
  {
    id: 'u4',
    email: 'owen.price@northstarfinance.com',
    firstName: 'Owen',
    lastName: 'Price',
    displayName: 'Owen Price',
    role: 'ar_specialist',
    status: 'active',
    entityIds: ['e1', 'e3'],
    primaryEntityId: 'e1',
    title: 'AR Specialist',
    createdAt: new Date('2024-02-18T09:00:00'),
    lastLoginAt: new Date('2026-04-04T07:45:00'),
  },
  {
    id: 'u5',
    email: 'nina.shah@northstarfinance.com',
    firstName: 'Nina',
    lastName: 'Shah',
    displayName: 'Nina Shah',
    role: 'cfo',
    status: 'active',
    entityIds: ['e1', 'e2', 'e3', 'e4'],
    primaryEntityId: 'e4',
    title: 'Chief Financial Officer',
    createdAt: new Date('2023-06-01T09:00:00'),
    lastLoginAt: new Date('2026-04-02T17:15:00'),
  },
  {
    id: 'u6',
    email: 'noah.wells@northstarfinance.com',
    firstName: 'Noah',
    lastName: 'Wells',
    displayName: 'Noah Wells',
    role: 'admin',
    status: 'active',
    entityIds: ['e1', 'e2', 'e3', 'e4'],
    primaryEntityId: 'e4',
    title: 'Platform Admin',
    createdAt: new Date('2023-05-11T09:00:00'),
    lastLoginAt: new Date('2026-04-01T15:00:00'),
  },
]

export const currentUser = users[0]
