import type {
  BudgetLine,
  BudgetSubmission,
  BudgetVersion,
  ForecastAssumption,
  ForecastDriver,
  ForecastScenario,
} from '@/lib/types'

export const budgetVersions: BudgetVersion[] = [
  {
    id: 'bud-2026-op-v1',
    name: 'FY26 Operating Plan v1',
    fiscalYear: 2026,
    entityId: 'e1',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-close',
    projectName: 'Q1 Close Acceleration',
    ownerId: 'u1',
    ownerName: 'Ava Mitchell',
    versionType: 'operating',
    status: 'in_review',
    totalBudget: 2860000,
    actualToDate: 842000,
    forecastAmount: 2915000,
    varianceAmount: 55000,
    variancePercent: 1.9,
    lineCount: 24,
    submissionDueDate: new Date('2026-04-09'),
    updatedAt: new Date('2026-04-04T09:20:00'),
    notes: 'Close support and audit readiness spend are above plan.',
  },
  {
    id: 'bud-2026-cap-v2',
    name: 'FY26 Capital Refresh v2',
    fiscalYear: 2026,
    entityId: 'e2',
    departmentId: 'd-ops',
    departmentName: 'Operations',
    ownerId: 'u2',
    ownerName: 'Miles Chen',
    versionType: 'capital',
    status: 'approved',
    totalBudget: 1380000,
    actualToDate: 264000,
    forecastAmount: 1325000,
    varianceAmount: -55000,
    variancePercent: -4,
    lineCount: 12,
    submissionDueDate: new Date('2026-04-12'),
    updatedAt: new Date('2026-04-03T16:15:00'),
    notes: 'West plant CNC refresh shifted into Q2.',
  },
  {
    id: 'bud-2026-eu-v1',
    name: 'FY26 EU Shared Services',
    fiscalYear: 2026,
    entityId: 'e3',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-eu',
    projectName: 'EU Shared Services',
    ownerId: 'u2',
    ownerName: 'Miles Chen',
    versionType: 'operating',
    status: 'draft',
    totalBudget: 720000,
    actualToDate: 196000,
    forecastAmount: 756000,
    varianceAmount: 36000,
    variancePercent: 5,
    lineCount: 18,
    submissionDueDate: new Date('2026-04-10'),
    updatedAt: new Date('2026-04-04T07:45:00'),
    notes: 'Shared services FX exposure still needs controller review.',
  },
  {
    id: 'bud-2026-headcount-v1',
    name: 'FY26 Headcount Replan',
    fiscalYear: 2026,
    entityId: 'e1',
    departmentId: 'd-it',
    departmentName: 'IT',
    projectId: 'p-erp',
    projectName: 'ERP Data Migration',
    ownerId: 'u6',
    ownerName: 'Noah Wells',
    versionType: 'headcount',
    status: 'locked',
    totalBudget: 940000,
    actualToDate: 301000,
    forecastAmount: 932000,
    varianceAmount: -8000,
    variancePercent: -0.9,
    lineCount: 10,
    submissionDueDate: new Date('2026-04-05'),
    updatedAt: new Date('2026-04-02T13:00:00'),
    notes: 'Hiring plan locked for ERP migration wave.',
  },
]

export const budgetLines: BudgetLine[] = [
  { id: 'bud-line-1', budgetVersionId: 'bud-2026-op-v1', accountId: 'a-payroll', accountName: 'Payroll Expense', category: 'Payroll', periodLabel: 'Apr 2026', departmentId: 'd-fin', departmentName: 'Finance', projectId: 'p-close', projectName: 'Q1 Close Acceleration', budgetAmount: 98000, actualAmount: 101500, forecastAmount: 103000 },
  { id: 'bud-line-2', budgetVersionId: 'bud-2026-op-v1', accountId: 'a-prof', accountName: 'Professional Services', category: 'Professional Services', periodLabel: 'Apr 2026', departmentId: 'd-fin', departmentName: 'Finance', projectId: 'p-close', projectName: 'Q1 Close Acceleration', budgetAmount: 12000, actualAmount: 18400, forecastAmount: 18650 },
  { id: 'bud-line-3', budgetVersionId: 'bud-2026-cap-v2', accountId: 'a-fixed', accountName: 'Machinery & Equipment', category: 'Capital Equipment', periodLabel: 'Apr 2026', departmentId: 'd-ops', departmentName: 'Operations', budgetAmount: 220000, actualAmount: 174000, forecastAmount: 182000 },
  { id: 'bud-line-4', budgetVersionId: 'bud-2026-cap-v2', accountId: 'a-dep', accountName: 'Depreciation Expense', category: 'Depreciation', periodLabel: 'Apr 2026', departmentId: 'd-ops', departmentName: 'Operations', budgetAmount: 26000, actualAmount: 24800, forecastAmount: 25200 },
  { id: 'bud-line-5', budgetVersionId: 'bud-2026-eu-v1', accountId: 'a-service', accountName: 'Service Revenue', category: 'Revenue', periodLabel: 'Apr 2026', departmentId: 'd-fin', departmentName: 'Finance', projectId: 'p-eu', projectName: 'EU Shared Services', budgetAmount: 84000, actualAmount: 79200, forecastAmount: 81500 },
  { id: 'bud-line-6', budgetVersionId: 'bud-2026-headcount-v1', accountId: 'a-payroll', accountName: 'Payroll Expense', category: 'Headcount', periodLabel: 'Apr 2026', departmentId: 'd-it', departmentName: 'IT', projectId: 'p-erp', projectName: 'ERP Data Migration', budgetAmount: 62000, actualAmount: 60400, forecastAmount: 61250 },
]

export const forecastScenarios: ForecastScenario[] = [
  {
    id: 'fcst-ops-upside',
    name: 'Upside Collections Recovery',
    entityId: 'e1',
    departmentId: 'd-sales',
    departmentName: 'Sales',
    projectId: 'p-close',
    projectName: 'Q1 Close Acceleration',
    basedOnBudgetVersionId: 'bud-2026-op-v1',
    ownerId: 'u1',
    ownerName: 'Ava Mitchell',
    status: 'active',
    confidence: 'medium',
    revenueForecast: 5410000,
    expenseForecast: 3015000,
    netForecast: 2395000,
    upsideAmount: 148000,
    downsideAmount: 64000,
    updatedAt: new Date('2026-04-04T09:05:00'),
  },
  {
    id: 'fcst-cap-constrained',
    name: 'Constrained Capital Spend',
    entityId: 'e2',
    departmentId: 'd-ops',
    departmentName: 'Operations',
    basedOnBudgetVersionId: 'bud-2026-cap-v2',
    ownerId: 'u2',
    ownerName: 'Miles Chen',
    status: 'approved',
    confidence: 'high',
    revenueForecast: 2975000,
    expenseForecast: 2140000,
    netForecast: 835000,
    upsideAmount: 42000,
    downsideAmount: 18000,
    updatedAt: new Date('2026-04-03T17:30:00'),
  },
  {
    id: 'fcst-eu-fx-watch',
    name: 'EU FX Watch',
    entityId: 'e3',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-eu',
    projectName: 'EU Shared Services',
    basedOnBudgetVersionId: 'bud-2026-eu-v1',
    ownerId: 'u2',
    ownerName: 'Miles Chen',
    status: 'in_review',
    confidence: 'low',
    revenueForecast: 268000,
    expenseForecast: 201000,
    netForecast: 67000,
    upsideAmount: 18000,
    downsideAmount: 36000,
    updatedAt: new Date('2026-04-04T08:10:00'),
  },
]

export const forecastDrivers: ForecastDriver[] = [
  { id: 'fcst-driver-1', scenarioId: 'fcst-ops-upside', name: 'Collections timing', type: 'revenue', assumption: 'Two strategic customers pay inside 15 days.', impactAmount: 98000, direction: 'increase' },
  { id: 'fcst-driver-2', scenarioId: 'fcst-ops-upside', name: 'Audit overrun', type: 'expense', assumption: 'Extended SOX scope through April.', impactAmount: 14000, direction: 'increase' },
  { id: 'fcst-driver-3', scenarioId: 'fcst-cap-constrained', name: 'CNC pushout', type: 'expense', assumption: 'Plant equipment refresh moves to late May.', impactAmount: 55000, direction: 'decrease' },
  { id: 'fcst-driver-4', scenarioId: 'fcst-eu-fx-watch', name: 'EUR/USD rates', type: 'price', assumption: 'FX settles at 1.06 by month end.', impactAmount: 22000, direction: 'decrease' },
]

export const forecastAssumptions: ForecastAssumption[] = [
  { id: 'fcst-assumption-1', scenarioId: 'fcst-ops-upside', label: 'Apex payment timing', value: '15 days', unit: 'DSO', status: 'approved', notes: 'Collections lead confirmed remittance window.' },
  { id: 'fcst-assumption-2', scenarioId: 'fcst-ops-upside', label: 'Close support burn', value: '18,650', unit: 'USD', status: 'needs_review', notes: 'Consulting invoices still arriving.' },
  { id: 'fcst-assumption-3', scenarioId: 'fcst-cap-constrained', label: 'Capex pushout', value: '55,000', unit: 'USD', status: 'approved' },
  { id: 'fcst-assumption-4', scenarioId: 'fcst-eu-fx-watch', label: 'FX sensitivity', value: '1.06', unit: 'EUR/USD', status: 'open', notes: 'Treasury team requested daily refresh.' },
]

export const budgetSubmissions: BudgetSubmission[] = [
  { id: 'bud-sub-1', budgetVersionId: 'bud-2026-op-v1', entityId: 'e1', departmentId: 'd-fin', departmentName: 'Finance', projectId: 'p-close', projectName: 'Q1 Close Acceleration', ownerId: 'u1', ownerName: 'Ava Mitchell', status: 'in_progress', dueDate: new Date('2026-04-09') },
  { id: 'bud-sub-2', budgetVersionId: 'bud-2026-cap-v2', entityId: 'e2', departmentId: 'd-ops', departmentName: 'Operations', ownerId: 'u2', ownerName: 'Miles Chen', status: 'submitted', dueDate: new Date('2026-04-12'), submittedAt: new Date('2026-04-03T18:00:00') },
  { id: 'bud-sub-3', budgetVersionId: 'bud-2026-eu-v1', entityId: 'e3', departmentId: 'd-fin', departmentName: 'Finance', projectId: 'p-eu', projectName: 'EU Shared Services', ownerId: 'u2', ownerName: 'Miles Chen', status: 'overdue', dueDate: new Date('2026-04-02'), exceptionReason: 'FX support note missing from submission pack.' },
  { id: 'bud-sub-4', budgetVersionId: 'bud-2026-headcount-v1', entityId: 'e1', departmentId: 'd-it', departmentName: 'IT', projectId: 'p-erp', projectName: 'ERP Data Migration', ownerId: 'u6', ownerName: 'Noah Wells', status: 'returned', dueDate: new Date('2026-04-05'), exceptionReason: 'Hiring ramp did not tie to approved requisition plan.' },
]
