import type { AIInsight, ApprovalItem, Workflow } from "@/lib/types"

export const approvalItems: ApprovalItem[] = [
  {
    id: "ap-3001",
    type: "journal_entry",
    documentId: "je-1003",
    documentNumber: "JE-2026-1003",
    description: "Payroll accrual requires controller approval",
    amount: 86000,
    currency: "USD",
    requestedBy: "Ava Mitchell",
    requestedAt: new Date("2026-03-27T11:30:00"),
    status: "pending",
    priority: "high",
    entityId: "e2",
  },
  {
    id: "ap-3002",
    type: "bill",
    documentId: "bill-7603",
    documentNumber: "BILL-7603",
    description: "Quarter-end software renewal is pending finance review",
    amount: 14500,
    currency: "USD",
    requestedBy: "Lena Garcia",
    requestedAt: new Date("2026-04-03T09:10:00"),
    status: "pending",
    priority: "medium",
    entityId: "e1",
  },
  {
    id: "ap-3003",
    type: "invoice",
    documentId: "inv-2008",
    documentNumber: "INV-2008",
    description: "Enterprise contract invoice is waiting on AR lead approval",
    amount: 38250,
    currency: "USD",
    requestedBy: "Owen Price",
    requestedAt: new Date("2026-04-04T08:25:00"),
    status: "pending",
    priority: "high",
    entityId: "e4",
  },
]

export const aiInsights: AIInsight[] = [
  {
    id: "ai1",
    type: "anomaly",
    severity: "warning",
    title: "Unusual expense pattern detected",
    description: "Marketing expenses increased 45% compared to the same period last year. This exceeds the typical variance threshold of 25%.",
    relatedIds: ["t2"],
    actionLabel: "Review Details",
    actionHref: "/reports/expense-analysis",
    createdAt: new Date("2026-04-03T08:00:00"),
  },
  {
    id: "ai2",
    type: "duplicate",
    severity: "critical",
    title: "Potential duplicate bill detected",
    description: "BILL-2024-001 appears to be similar to BILL-2024-003 from the same vendor with matching amounts.",
    relatedIds: ["b1", "b3"],
    actionLabel: "Compare Bills",
    actionHref: "/accounts-payable/bills?compare=b1,b3",
    createdAt: new Date("2026-04-02T14:30:00"),
  },
  {
    id: "ai3",
    type: "missing_receipt",
    severity: "warning",
    title: "3 expenses missing receipts",
    description: "Three expense transactions over $500 are missing attached receipts, which may impact audit compliance.",
    actionLabel: "View Expenses",
    actionHref: "/time-expenses/expense-reports?missing=receipts",
    createdAt: new Date("2026-04-02T10:00:00"),
  },
  {
    id: "ai4",
    type: "budget_variance",
    severity: "info",
    title: "Revenue tracking below budget",
    description: "YTD revenue is 6.2% below budget. At current trajectory, annual revenue may miss target by $780K.",
    actionLabel: "View Forecast",
    actionHref: "/reports/budget-forecast",
    createdAt: new Date("2026-04-01T16:00:00"),
  },
  {
    id: "ai5",
    type: "recommendation",
    severity: "info",
    title: "Early payment discount opportunity",
    description: "4 bills totaling $45,000 qualify for 2% early payment discounts if paid within 10 days, saving $900.",
    actionLabel: "Review Bills",
    actionHref: "/accounts-payable/bills?discount=available",
    createdAt: new Date("2026-03-31T11:00:00"),
  },
]

export const workflows: Workflow[] = [
  {
    id: "wf1",
    name: "Bill Approval > $5,000",
    type: "approval",
    trigger: "bill.created",
    status: "active",
    steps: [
      { id: "s1", order: 1, type: "condition", config: { field: "amount", operator: "gte", value: 5000 } },
      { id: "s2", order: 2, type: "approval", config: { role: "controller" } },
    ],
    entityIds: ["e1", "e2"],
    createdBy: "Sarah Chen",
    createdAt: new Date("2026-02-01T10:00:00"),
  },
  {
    id: "wf2",
    name: "Invoice Overdue Notification",
    type: "notification",
    trigger: "invoice.overdue",
    status: "active",
    steps: [{ id: "s1", order: 1, type: "notification", config: { channel: "email", template: "overdue_invoice" } }],
    entityIds: ["e1"],
    createdBy: "Michael Johnson",
    createdAt: new Date("2026-02-12T11:15:00"),
  },
  {
    id: "wf3",
    name: "Journal Entry Auto-Post",
    type: "automation",
    trigger: "journal_entry.approved",
    status: "active",
    steps: [{ id: "s1", order: 1, type: "action", config: { action: "post" } }],
    entityIds: ["e1", "e2", "e3"],
    createdBy: "Sarah Chen",
    createdAt: new Date("2026-02-20T09:00:00"),
  },
  {
    id: "wf4",
    name: "Expense Report Approval",
    type: "approval",
    trigger: "expense.submitted",
    status: "inactive",
    steps: [
      { id: "s1", order: 1, type: "approval", config: { role: "manager" } },
      { id: "s2", order: 2, type: "condition", config: { field: "amount", operator: "gte", value: 1000 } },
      { id: "s3", order: 3, type: "approval", config: { role: "controller" } },
    ],
    entityIds: ["e1"],
    createdBy: "Emily Davis",
    createdAt: new Date("2026-03-01T13:00:00"),
  },
  {
    id: "wf5",
    name: "Payment Confirmation",
    type: "notification",
    trigger: "payment.completed",
    status: "draft",
    steps: [{ id: "s1", order: 1, type: "notification", config: { channel: "email", template: "payment_confirmation" } }],
    entityIds: ["e1"],
    createdBy: "Sarah Chen",
    createdAt: new Date("2026-03-20T15:30:00"),
  },
]
