import type {
  ApiRequestLog,
  CustomFieldDefinition,
  DeliveryTarget,
  DeveloperApp,
  EventMonitoringRecord,
  ExportJob,
  ExportSchedule,
  IntegrationDependency,
  IntegrationSyncRun,
  NotificationPolicy,
  RuleDefinition,
  RuleDeployment,
  RuleSimulationResult,
  ShareLink,
  WebhookEndpoint,
} from '@/lib/types'

export const customFieldDefinitions: CustomFieldDefinition[] = [
  {
    id: 'cf-po-number',
    name: 'Purchase Order Number',
    code: 'PO_NUM',
    type: 'text',
    module: 'bill',
    required: false,
    status: 'active',
    entityId: 'e1',
    createdAt: new Date('2026-01-10T10:00:00'),
    updatedAt: new Date('2026-03-28T14:15:00'),
  },
  {
    id: 'cf-contract-ref',
    name: 'Contract Reference',
    code: 'CONTRACT_REF',
    type: 'text',
    module: 'invoice',
    required: false,
    status: 'active',
    entityId: 'e2',
    createdAt: new Date('2026-01-12T09:30:00'),
    updatedAt: new Date('2026-03-25T11:00:00'),
  },
  {
    id: 'cf-sales-region',
    name: 'Sales Region',
    code: 'SALES_REGION',
    type: 'dropdown',
    module: 'customer',
    required: true,
    status: 'active',
    options: ['North', 'South', 'East', 'West'],
    entityId: 'e4',
    createdAt: new Date('2026-01-20T08:45:00'),
    updatedAt: new Date('2026-03-20T16:00:00'),
  },
  {
    id: 'cf-tax-exempt',
    name: 'Tax Exempt',
    code: 'TAX_EXEMPT',
    type: 'boolean',
    module: 'vendor',
    required: false,
    status: 'active',
    entityId: 'e4',
    createdAt: new Date('2026-02-05T13:00:00'),
    updatedAt: new Date('2026-03-10T10:20:00'),
  },
  {
    id: 'cf-project-start',
    name: 'Project Start Date',
    code: 'PROJ_START',
    type: 'date',
    module: 'project',
    required: true,
    status: 'active',
    entityId: 'e1',
    createdAt: new Date('2026-02-16T15:15:00'),
    updatedAt: new Date('2026-03-22T09:10:00'),
  },
  {
    id: 'cf-internal-notes',
    name: 'Internal Notes',
    code: 'INTERNAL_NOTES',
    type: 'textarea',
    module: 'journal_entry',
    required: false,
    status: 'inactive',
    entityId: 'e3',
    createdAt: new Date('2026-02-21T11:45:00'),
    updatedAt: new Date('2026-03-18T17:45:00'),
  },
]

export const notificationPolicies: NotificationPolicy[] = [
  {
    id: 'np-approvals-required',
    category: 'approvals',
    name: 'Approval Required',
    description: 'Send an alert when a document requires review.',
    email: true,
    push: true,
    frequency: 'instant',
    scope: 'role',
    roleIds: ['accountant', 'controller', 'admin'],
    updatedAt: new Date('2026-03-30T09:00:00'),
  },
  {
    id: 'np-approvals-completed',
    category: 'approvals',
    name: 'Approval Completed',
    description: 'Notify originators when approvals complete.',
    email: true,
    push: false,
    frequency: 'instant',
    scope: 'global',
    updatedAt: new Date('2026-03-28T12:00:00'),
  },
  {
    id: 'np-task-overdue',
    category: 'tasks',
    name: 'Task Overdue',
    description: 'Escalate overdue close tasks and owner assignments.',
    email: true,
    push: true,
    frequency: 'instant',
    scope: 'role',
    roleIds: ['accountant', 'controller'],
    updatedAt: new Date('2026-04-02T07:30:00'),
  },
  {
    id: 'np-payment-failed',
    category: 'payments',
    name: 'Payment Failed',
    description: 'Raise payment failures to AP and treasury operators.',
    email: true,
    push: true,
    frequency: 'instant',
    scope: 'role',
    roleIds: ['accountant', 'ap_specialist', 'controller'],
    updatedAt: new Date('2026-03-31T10:45:00'),
  },
  {
    id: 'np-invoice-overdue',
    category: 'invoices',
    name: 'Invoice Overdue',
    description: 'Send daily collection reminders for overdue AR.',
    email: true,
    push: false,
    frequency: 'daily',
    scope: 'role',
    roleIds: ['accountant', 'ar_specialist', 'controller'],
    updatedAt: new Date('2026-03-29T14:20:00'),
  },
  {
    id: 'np-sync-errors',
    category: 'system',
    name: 'Sync Errors',
    description: 'Alert platform owners when integrations fail or stall.',
    email: true,
    push: true,
    frequency: 'instant',
    scope: 'global',
    updatedAt: new Date('2026-04-01T18:10:00'),
  },
  {
    id: 'np-security-alerts',
    category: 'system',
    name: 'Security Alerts',
    description: 'Immediate security event notifications for administrators.',
    email: true,
    push: true,
    frequency: 'instant',
    scope: 'role',
    roleIds: ['admin'],
    updatedAt: new Date('2026-04-03T08:10:00'),
  },
]

export const integrationSyncRuns: IntegrationSyncRun[] = [
  {
    id: 'sync-1',
    integrationId: 'int1',
    integrationName: 'Chase Bank',
    status: 'success',
    source: 'scheduled',
    startedAt: new Date('2026-04-05T05:00:00'),
    finishedAt: new Date('2026-04-05T05:02:00'),
    recordsProcessed: 248,
    errorCount: 0,
    entityId: 'e1',
    summary: 'Daily bank feed completed with no unreconciled failures.',
  },
  {
    id: 'sync-2',
    integrationId: 'int5',
    integrationName: 'Shopify',
    status: 'failed',
    source: 'webhook',
    startedAt: new Date('2026-04-04T16:10:00'),
    finishedAt: new Date('2026-04-04T16:12:00'),
    recordsProcessed: 18,
    errorCount: 6,
    entityId: 'e2',
    summary: 'Order sync failed on tax mapping for west-region storefront.',
  },
  {
    id: 'sync-3',
    integrationId: 'int4',
    integrationName: 'Salesforce CRM',
    status: 'warning',
    source: 'manual',
    startedAt: new Date('2026-04-05T07:20:00'),
    finishedAt: new Date('2026-04-05T07:28:00'),
    recordsProcessed: 92,
    errorCount: 2,
    entityId: 'e4',
    summary: 'Opportunities synced with 2 customer matching exceptions.',
  },
  {
    id: 'sync-4',
    integrationId: 'int8',
    integrationName: 'BambooHR',
    status: 'running',
    source: 'scheduled',
    startedAt: new Date('2026-04-05T09:00:00'),
    recordsProcessed: 36,
    errorCount: 0,
    entityId: 'e4',
    summary: 'Employee dimension refresh is still in progress.',
  },
  {
    id: 'sync-5',
    integrationId: 'int6',
    integrationName: 'Avalara Tax',
    status: 'success',
    source: 'scheduled',
    startedAt: new Date('2026-04-04T22:00:00'),
    finishedAt: new Date('2026-04-04T22:03:00'),
    recordsProcessed: 122,
    errorCount: 0,
    entityId: 'e4',
    summary: 'Tax jurisdiction updates completed for all active entities.',
  },
]

export const integrationDependencies: IntegrationDependency[] = [
  {
    id: 'dep-1',
    integrationId: 'int1',
    label: 'Cash Reconciliation Queue',
    type: 'module',
    status: 'healthy',
    description: 'Feeds matched and unmatched bank activity to the accountant queue.',
  },
  {
    id: 'dep-2',
    integrationId: 'int5',
    label: 'Revenue Schedule Builder',
    type: 'module',
    status: 'blocked',
    description: 'Revenue schedule imports are blocked until tax mapping exceptions clear.',
  },
  {
    id: 'dep-3',
    integrationId: 'int4',
    label: 'Customer Sync Workflow',
    type: 'workflow',
    status: 'degraded',
    description: 'Customer enrichment is active but duplicate handling is delayed.',
  },
  {
    id: 'dep-4',
    integrationId: 'int6',
    label: 'Indirect Tax Export',
    type: 'export',
    status: 'healthy',
    description: 'Daily tax package exports are on schedule.',
  },
  {
    id: 'dep-5',
    integrationId: 'int8',
    label: 'Employee Master Webhook',
    type: 'webhook',
    status: 'degraded',
    description: 'Webhook retries are queued for new-hire cost center assignments.',
  },
]

export const developerApps: DeveloperApp[] = [
  {
    id: 'app-1',
    name: 'Treasury Console',
    status: 'active',
    ownerName: 'Platform Team',
    clientId: 'cli_treasury_prod',
    environment: 'production',
    scopes: ['cash.read', 'reconciliation.manage', 'exports.read'],
    createdAt: new Date('2026-01-14T11:00:00'),
    lastUsedAt: new Date('2026-04-05T08:30:00'),
  },
  {
    id: 'app-2',
    name: 'Planning Sync Worker',
    status: 'active',
    ownerName: 'FP&A Engineering',
    clientId: 'cli_planning_worker',
    environment: 'production',
    scopes: ['budgets.read', 'budgets.write', 'reports.read'],
    createdAt: new Date('2026-02-02T09:45:00'),
    lastUsedAt: new Date('2026-04-04T18:10:00'),
  },
  {
    id: 'app-3',
    name: 'Revenue QA Sandbox',
    status: 'draft',
    ownerName: 'Revenue Ops',
    clientId: 'cli_revops_sandbox',
    environment: 'sandbox',
    scopes: ['contracts.read', 'revenue.read'],
    createdAt: new Date('2026-03-12T14:10:00'),
  },
  {
    id: 'app-4',
    name: 'Legacy Data Pump',
    status: 'suspended',
    ownerName: 'Admin Team',
    clientId: 'cli_legacy_pump',
    environment: 'production',
    scopes: ['transactions.read'],
    createdAt: new Date('2025-11-01T12:00:00'),
    lastUsedAt: new Date('2026-03-22T06:00:00'),
  },
]

export const webhookEndpoints: WebhookEndpoint[] = [
  {
    id: 'webhook-1',
    name: 'Bank Feed Listener',
    url: 'https://hooks.northstar.example/bank-feed',
    eventType: 'bank.transaction.created',
    status: 'active',
    signingKey: 'whsec_bankfeed_primary',
    retryCount: 0,
    lastDeliveredAt: new Date('2026-04-05T07:12:00'),
    createdAt: new Date('2026-01-15T11:45:00'),
  },
  {
    id: 'webhook-2',
    name: 'Billing Delivery',
    url: 'https://hooks.northstar.example/billing',
    eventType: 'invoice.sent',
    status: 'active',
    signingKey: 'whsec_billing_primary',
    retryCount: 1,
    lastDeliveredAt: new Date('2026-04-05T06:55:00'),
    createdAt: new Date('2026-01-20T09:00:00'),
  },
  {
    id: 'webhook-3',
    name: 'ERP Export Failed Events',
    url: 'https://hooks.northstar.example/exports',
    eventType: 'export.failed',
    status: 'error',
    signingKey: 'whsec_exports_failover',
    retryCount: 5,
    lastDeliveredAt: new Date('2026-04-04T21:00:00'),
    createdAt: new Date('2026-02-14T16:30:00'),
  },
]

export const apiRequestLogs: ApiRequestLog[] = [
  {
    id: 'req-1',
    endpoint: '/v1/reconciliation/runs',
    method: 'POST',
    statusCode: 201,
    latencyMs: 284,
    apiKeyId: 'ak1',
    appId: 'app-1',
    entityId: 'e1',
    success: true,
    createdAt: new Date('2026-04-05T08:41:00'),
  },
  {
    id: 'req-2',
    endpoint: '/v1/contracts/schedules',
    method: 'GET',
    statusCode: 200,
    latencyMs: 118,
    apiKeyId: 'ak2',
    appId: 'app-2',
    entityId: 'e4',
    success: true,
    createdAt: new Date('2026-04-05T08:15:00'),
  },
  {
    id: 'req-3',
    endpoint: '/v1/exports/jobs',
    method: 'POST',
    statusCode: 429,
    latencyMs: 42,
    apiKeyId: 'ak3',
    appId: 'app-4',
    entityId: 'e4',
    success: false,
    createdAt: new Date('2026-04-05T07:48:00'),
  },
  {
    id: 'req-4',
    endpoint: '/v1/budgets/scenarios',
    method: 'PUT',
    statusCode: 202,
    latencyMs: 364,
    apiKeyId: 'ak2',
    appId: 'app-2',
    entityId: 'e2',
    success: true,
    createdAt: new Date('2026-04-04T19:50:00'),
  },
  {
    id: 'req-5',
    endpoint: '/v1/webhooks/events',
    method: 'POST',
    statusCode: 500,
    latencyMs: 610,
    appId: 'app-3',
    entityId: 'e4',
    success: false,
    createdAt: new Date('2026-04-04T18:08:00'),
  },
]

export const ruleDefinitions: RuleDefinition[] = [
  {
    id: 'rule-1',
    name: 'Auto-route bills over $25K',
    category: 'approval',
    status: 'active',
    trigger: 'bill.created',
    conditionSummary: 'Amount >= 25,000 and department = Ops',
    actionSummary: 'Route to controller then CFO',
    priority: 10,
    entityId: 'e1',
    ownerName: 'Ava Mitchell',
    updatedAt: new Date('2026-04-04T11:00:00'),
    matchCount: 48,
  },
  {
    id: 'rule-2',
    name: 'Flag missing contract support',
    category: 'exception',
    status: 'active',
    trigger: 'revenue.schedule.created',
    conditionSummary: 'Missing signed contract or amendment',
    actionSummary: 'Place schedule on hold and notify revenue ops',
    priority: 8,
    entityId: 'e4',
    ownerName: 'Miles Chen',
    updatedAt: new Date('2026-04-03T16:20:00'),
    matchCount: 12,
  },
  {
    id: 'rule-3',
    name: 'Cash feed transaction routing',
    category: 'routing',
    status: 'paused',
    trigger: 'bank.transaction.created',
    conditionSummary: 'Merchant text contains payroll provider',
    actionSummary: 'Route to payroll clearing account',
    priority: 6,
    entityId: 'e2',
    ownerName: 'Jordan Lee',
    updatedAt: new Date('2026-03-30T09:40:00'),
    matchCount: 102,
  },
  {
    id: 'rule-4',
    name: 'Monthly close export package',
    category: 'export',
    status: 'draft',
    trigger: 'period.close.ready',
    conditionSummary: 'Entity in active close calendar',
    actionSummary: 'Queue board package and audit extract',
    priority: 4,
    entityId: 'e4',
    ownerName: 'Priya Shah',
    updatedAt: new Date('2026-04-02T14:05:00'),
    matchCount: 0,
  },
]

export const ruleSimulationResults: RuleSimulationResult[] = [
  {
    id: 'sim-1',
    ruleId: 'rule-1',
    ruleName: 'Auto-route bills over $25K',
    status: 'passed',
    sampleRecord: 'BILL-2026-104',
    outcome: 'Escalated to controller and CFO approval chain.',
    entityId: 'e1',
    createdAt: new Date('2026-04-05T06:45:00'),
  },
  {
    id: 'sim-2',
    ruleId: 'rule-2',
    ruleName: 'Flag missing contract support',
    status: 'warning',
    sampleRecord: 'SCH-REV-221',
    outcome: 'Schedule placed on hold; support gap identified.',
    entityId: 'e4',
    createdAt: new Date('2026-04-04T13:20:00'),
  },
  {
    id: 'sim-3',
    ruleId: 'rule-3',
    ruleName: 'Cash feed transaction routing',
    status: 'failed',
    sampleRecord: 'BANK-TRX-8842',
    outcome: 'Routing keyword missed because merchant memo changed format.',
    entityId: 'e2',
    createdAt: new Date('2026-04-04T08:05:00'),
  },
]

export const ruleDeployments: RuleDeployment[] = [
  {
    id: 'dep-rule-1',
    ruleId: 'rule-1',
    ruleName: 'Auto-route bills over $25K',
    environment: 'production',
    status: 'active',
    deployedBy: 'Ava Mitchell',
    deployedAt: new Date('2026-04-01T10:10:00'),
    version: 'v12',
  },
  {
    id: 'dep-rule-2',
    ruleId: 'rule-2',
    ruleName: 'Flag missing contract support',
    environment: 'production',
    status: 'active',
    deployedBy: 'Miles Chen',
    deployedAt: new Date('2026-04-02T09:00:00'),
    version: 'v4',
  },
  {
    id: 'dep-rule-3',
    ruleId: 'rule-3',
    ruleName: 'Cash feed transaction routing',
    environment: 'sandbox',
    status: 'pending',
    deployedBy: 'Jordan Lee',
    deployedAt: new Date('2026-04-04T17:15:00'),
    version: 'v7',
  },
]

export const deliveryTargets: DeliveryTarget[] = [
  {
    id: 'target-1',
    type: 'email',
    label: 'Board Distribution List',
    destination: 'board-finance@northstar.example',
    status: 'active',
  },
  {
    id: 'target-2',
    type: 's3',
    label: 'Audit Archive Bucket',
    destination: 's3://northstar-audit-archive/month-end',
    status: 'active',
  },
  {
    id: 'target-3',
    type: 'share_link',
    label: 'Controller Shared Room',
    destination: 'share://controller-close-room',
    status: 'active',
  },
  {
    id: 'target-4',
    type: 'api',
    label: 'Treasury Delivery API',
    destination: 'https://api.northstar.example/v1/exports/receive',
    status: 'error',
  },
]

export const exportJobs: ExportJob[] = [
  {
    id: 'job-1',
    name: 'Month-End Board Package',
    module: 'reports',
    format: 'pdf',
    status: 'completed',
    requestedBy: 'Miles Chen',
    createdAt: new Date('2026-04-05T07:10:00'),
    deliveredAt: new Date('2026-04-05T07:14:00'),
    entityId: 'e4',
    recordCount: 12,
  },
  {
    id: 'job-2',
    name: 'Open AR Workbook',
    module: 'accounts-receivable',
    format: 'xlsx',
    status: 'processing',
    requestedBy: 'Owen Price',
    createdAt: new Date('2026-04-05T08:10:00'),
    entityId: 'e2',
    recordCount: 148,
  },
  {
    id: 'job-3',
    name: 'Rule Exception Extract',
    module: 'rule-engine',
    format: 'csv',
    status: 'failed',
    requestedBy: 'Priya Shah',
    createdAt: new Date('2026-04-04T21:05:00'),
    entityId: 'e4',
    recordCount: 64,
  },
  {
    id: 'job-4',
    name: 'Cash Position Snapshot',
    module: 'cash-management',
    format: 'pdf',
    status: 'scheduled',
    requestedBy: 'Ava Mitchell',
    createdAt: new Date('2026-04-03T18:00:00'),
    entityId: 'e1',
    recordCount: 1,
  },
]

export const exportSchedules: ExportSchedule[] = [
  {
    id: 'schedule-1',
    name: 'Weekly AR Collections Pack',
    module: 'accounts-receivable',
    frequency: 'weekly',
    status: 'active',
    format: 'xlsx',
    nextRunAt: new Date('2026-04-08T06:00:00'),
    targetId: 'target-1',
    entityId: 'e4',
  },
  {
    id: 'schedule-2',
    name: 'Daily Cash Monitoring Feed',
    module: 'cash-management',
    frequency: 'daily',
    status: 'active',
    format: 'csv',
    nextRunAt: new Date('2026-04-06T04:00:00'),
    targetId: 'target-4',
    entityId: 'e1',
  },
  {
    id: 'schedule-3',
    name: 'Monthly Audit Archive',
    module: 'admin',
    frequency: 'monthly',
    status: 'paused',
    format: 'pdf',
    nextRunAt: new Date('2026-05-01T02:00:00'),
    targetId: 'target-2',
    entityId: 'e4',
  },
]

export const shareLinks: ShareLink[] = [
  {
    id: 'share-1',
    name: 'Controller Close Review',
    module: 'reports',
    status: 'active',
    url: 'https://share.northstar.example/close/review',
    createdBy: 'Miles Chen',
    createdAt: new Date('2026-04-02T09:10:00'),
    expiresAt: new Date('2026-04-12T23:59:00'),
    recipientSummary: '6 recipients',
  },
  {
    id: 'share-2',
    name: 'Revenue Exception Pack',
    module: 'contracts-revenue',
    status: 'active',
    url: 'https://share.northstar.example/revenue/exceptions',
    createdBy: 'Ava Mitchell',
    createdAt: new Date('2026-04-04T15:00:00'),
    recipientSummary: 'Revenue ops + controller',
  },
  {
    id: 'share-3',
    name: 'Vendor Audit Extract',
    module: 'accounts-payable',
    status: 'expired',
    url: 'https://share.northstar.example/ap/audit',
    createdBy: 'Jordan Lee',
    createdAt: new Date('2026-03-12T10:30:00'),
    expiresAt: new Date('2026-03-19T10:30:00'),
    recipientSummary: 'External audit team',
  },
]

export const eventMonitoringRecords: EventMonitoringRecord[] = [
  {
    id: 'evt-1',
    sourceType: 'integration',
    sourceId: 'int5',
    sourceLabel: 'Shopify',
    severity: 'critical',
    status: 'new',
    entityId: 'e2',
    occurredAt: new Date('2026-04-05T08:05:00'),
    message: 'Sales order sync stopped on tax code mismatch for west storefront.',
    resolutionHint: 'Remap tax jurisdiction and replay queued orders.',
  },
  {
    id: 'evt-2',
    sourceType: 'webhook',
    sourceId: 'webhook-3',
    sourceLabel: 'ERP Export Failed Events',
    severity: 'warning',
    status: 'retrying',
    entityId: 'e4',
    occurredAt: new Date('2026-04-05T07:52:00'),
    message: 'Webhook delivery timed out during share-link export failure notification.',
    resolutionHint: 'Check destination endpoint latency and retry queue.',
  },
  {
    id: 'evt-3',
    sourceType: 'rule',
    sourceId: 'rule-3',
    sourceLabel: 'Cash feed transaction routing',
    severity: 'warning',
    status: 'acknowledged',
    entityId: 'e2',
    occurredAt: new Date('2026-04-04T18:10:00'),
    message: 'Routing rule missed a payroll clearing transaction pattern.',
    resolutionHint: 'Update merchant memo condition or add fallback rule.',
  },
  {
    id: 'evt-4',
    sourceType: 'export',
    sourceId: 'job-3',
    sourceLabel: 'Rule Exception Extract',
    severity: 'critical',
    status: 'new',
    entityId: 'e4',
    occurredAt: new Date('2026-04-04T21:08:00'),
    message: 'CSV export failed while writing exception detail package.',
    resolutionHint: 'Re-run export after S3 delivery target is healthy.',
  },
  {
    id: 'evt-5',
    sourceType: 'workflow',
    sourceId: 'wf5',
    sourceLabel: 'Payment Confirmation',
    severity: 'info',
    status: 'resolved',
    entityId: 'e1',
    occurredAt: new Date('2026-04-03T13:25:00'),
    message: 'Workflow draft published after notification template refresh.',
    resolutionHint: 'No follow-up required.',
  },
  {
    id: 'evt-6',
    sourceType: 'api',
    sourceId: 'req-5',
    sourceLabel: 'Webhook API',
    severity: 'critical',
    status: 'acknowledged',
    entityId: 'e4',
    occurredAt: new Date('2026-04-04T18:08:00'),
    message: 'Developer sandbox request returned 500 on webhook replay.',
    resolutionHint: 'Inspect sandbox payload contract and replay trace.',
  },
]
