import type {
  RoleId,
  RoleShellConfig,
  ShellBreadcrumbDefinition,
  ShellCommandGroup,
  ShellDatePresetOption,
  ShellModule,
  ShellSidebarSection,
  ShellStubPage,
} from '@/lib/types'

const allPrimaryRoles: RoleId[] = ['accountant', 'ap_specialist', 'ar_specialist', 'controller', 'cfo', 'admin']
const operatorRoles: RoleId[] = ['accountant', 'ap_specialist', 'ar_specialist', 'controller']

export const shellDatePresetOptions: ShellDatePresetOption[] = [
  { value: 'today', label: 'Today' },
  { value: 'this_week', label: 'This Week' },
  { value: 'this_month', label: 'This Month' },
  { value: 'this_quarter', label: 'This Quarter' },
  { value: 'this_year', label: 'This Fiscal Year' },
  { value: 'last_month', label: 'Last Month' },
  { value: 'last_quarter', label: 'Last Quarter' },
  { value: 'last_year', label: 'Last Fiscal Year' },
]

export const shellModules: ShellModule[] = [
  {
    id: 'home',
    label: 'Home',
    icon: 'LayoutGrid',
    href: '/',
    description: 'Role-based workspace landing.',
    roles: allPrimaryRoles,
    matchers: ['/'],
  },
  {
    id: 'work-queue',
    label: 'Work Queue',
    icon: 'Inbox',
    href: '/work-queue',
    description: 'Operator queues, approvals, exceptions, and close-critical tasks.',
    roles: operatorRoles,
    matchers: ['/work-queue', '/tasks', '/approvals', '/activity', '/notifications', '/favorites'],
    groups: [
      {
        id: 'wq-operate',
        label: 'Operate',
        items: [
          { id: 'wq-home', label: 'Work Queue', href: '/work-queue', description: 'Unified queue for close, exceptions, and reviews.' },
          { id: 'wq-approvals', label: 'Approvals', href: '/approvals', description: 'Documents waiting on review and release.' },
          { id: 'wq-tasks', label: 'Task Board', href: '/tasks', description: 'Assigned work and due dates by operator.' },
        ],
      },
      {
        id: 'wq-monitor',
        label: 'Monitor',
        items: [
          { id: 'wq-activity', label: 'Activity', href: '/activity', description: 'Recent finance events and workflow movement.' },
          { id: 'wq-notifications', label: 'Notifications', href: '/notifications', description: 'Unread alerts and system follow-up.' },
          { id: 'wq-favorites', label: 'Favorites', href: '/favorites', description: 'Pinned reports and frequent destinations.' },
          { id: 'wq-documents', label: 'Documents', href: '/documents', description: 'Source documents, attachments, and receipts.' },
        ],
      },
    ],
  },
  {
    id: 'general-ledger',
    label: 'General Ledger',
    icon: 'BookOpenText',
    href: '/general-ledger',
    description: 'Journals, periods, allocations, and ledger control.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/general-ledger'],
    groups: [
      {
        id: 'gl-operate',
        label: 'Operate',
        items: [
          { id: 'gl-journals', label: 'Journal Entries', href: '/general-ledger/journal-entries', description: 'Prepare, review, and post journals.' },
          { id: 'gl-recurring', label: 'Recurring Journals', href: '/general-ledger/recurring-journals', description: 'Manage scheduled journal activity.' },
          { id: 'gl-periods', label: 'Accounting Periods', href: '/general-ledger/accounting-periods', description: 'Control open and close status by period.' },
        ],
      },
      {
        id: 'gl-structure',
        label: 'Structure',
        items: [
          { id: 'gl-coa', label: 'Chart of Accounts', href: '/general-ledger/chart-of-accounts', description: 'Maintain the reporting structure.' },
          { id: 'gl-allocations', label: 'Allocations', href: '/general-ledger/allocations', description: 'Run and govern allocation rules.' },
          { id: 'gl-audit', label: 'Audit Trail', href: '/general-ledger/audit-trail', description: 'Trace postings and control actions.' },
        ],
      },
      {
        id: 'gl-assurance',
        label: 'Assurance',
        items: [
          { id: 'gl-trial-balance', label: 'Trial Balance', href: '/general-ledger/reports/trial-balance', description: 'Validate balances before reporting.' },
          { id: 'gl-close-management', label: 'Close Management', href: '/general-ledger/close-management', description: 'Track period close progress and tasks.' },
        ],
      },
    ],
  },
  {
    id: 'accounts-payable',
    label: 'Accounts Payable',
    icon: 'ReceiptText',
    href: '/accounts-payable',
    description: 'Vendor, bill, approval, and payment operations.',
    roles: ['accountant', 'ap_specialist', 'controller', 'cfo', 'admin'],
    matchers: ['/accounts-payable'],
    groups: [
      {
        id: 'ap-process',
        label: 'Process',
        items: [
          { id: 'ap-bills', label: 'Bills', href: '/accounts-payable/bills', description: 'Capture, code, and route vendor bills.' },
          { id: 'ap-payments', label: 'Payments', href: '/accounts-payable/payments', description: 'Prepare and monitor disbursements.' },
          { id: 'ap-approvals', label: 'Approvals', href: '/accounts-payable/approvals', description: 'Manage AP approval routing.' },
        ],
      },
      {
        id: 'ap-master',
        label: 'Master Data',
        items: [
          { id: 'ap-vendors', label: 'Vendors', href: '/accounts-payable/vendors', description: 'Maintain vendor profiles and terms.' },
          { id: 'ap-aging', label: 'AP Aging', href: '/accounts-payable/aging', description: 'Review due buckets and exposure.' },
        ],
      },
    ],
  },
  {
    id: 'accounts-receivable',
    label: 'Accounts Receivable',
    icon: 'WalletCards',
    href: '/accounts-receivable',
    description: 'Invoicing, collections, customer balances, and cash application.',
    roles: ['accountant', 'ar_specialist', 'controller', 'cfo', 'admin'],
    matchers: ['/accounts-receivable'],
    groups: [
      {
        id: 'ar-process',
        label: 'Process',
        items: [
          { id: 'ar-invoices', label: 'Invoices', href: '/accounts-receivable/invoices', description: 'Issue and manage customer invoices.' },
          { id: 'ar-receipts', label: 'Receipts', href: '/accounts-receivable/receipts', description: 'Apply incoming cash and remittance.' },
          { id: 'ar-collections', label: 'Collections', href: '/accounts-receivable/collections', description: 'Track overdue accounts and follow-up.' },
        ],
      },
      {
        id: 'ar-master',
        label: 'Master Data',
        items: [
          { id: 'ar-customers', label: 'Customers', href: '/accounts-receivable/customers', description: 'Review credit, contacts, and balances.' },
          { id: 'ar-aging', label: 'AR Aging', href: '/accounts-receivable/aging', description: 'Prioritize receivables by age bucket.' },
        ],
      },
    ],
  },
  {
    id: 'cash-management',
    label: 'Cash',
    icon: 'Landmark',
    href: '/cash-management',
    description: 'Bank activity, transfers, and reconciliation control.',
    roles: ['accountant', 'ap_specialist', 'ar_specialist', 'controller', 'cfo', 'admin'],
    matchers: ['/cash-management'],
    groups: [
      {
        id: 'cash-operations',
        label: 'Cash Operations',
        items: [
          { id: 'cash-home', label: 'Overview', href: '/cash-management', description: 'Cash position and bank-monitoring workspace.' },
          { id: 'cash-transactions', label: 'Transactions', href: '/cash-management/transactions', description: 'Bank-feed and treasury activity.' },
          { id: 'cash-transfers', label: 'Transfers', href: '/cash-management/transfers', description: 'Entity and bank movement tracking.' },
        ],
      },
      {
        id: 'cash-control',
        label: 'Control',
        items: [
          { id: 'cash-reconciliation', label: 'Reconciliation', href: '/cash-management/reconciliation', description: 'Match, clear, and investigate breaks.' },
          { id: 'cash-accounts', label: 'Bank Accounts', href: '/cash-management/accounts', description: 'Bank accounts and balances by entity.' },
          { id: 'cash-card-feed', label: 'Card Feed', href: '/cash-management/card-feed', description: 'Corporate card expenses and receipts.' },
        ],
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reporting',
    icon: 'LineChart',
    href: '/reports',
    description: 'Financial statements, analytics, and report design.',
    roles: allPrimaryRoles,
    matchers: ['/reports'],
    groups: [
      {
        id: 'reports-financial',
        label: 'Financial Statements',
        items: [
          { id: 'rep-home', label: 'Report Library', href: '/reports', description: 'Browse financial and management reports.' },
          { id: 'rep-pnl', label: 'Income Statement', href: '/reports/income-statement', description: 'Profitability by period and entity.' },
          { id: 'rep-bs', label: 'Balance Sheet', href: '/reports/balance-sheet', description: 'Ending balances and structure.' },
          { id: 'rep-cf', label: 'Cash Flow', href: '/reports/cash-flow', description: 'Operating, investing, and financing movement.' },
        ],
      },
      {
        id: 'reports-analysis',
        label: 'Analysis',
        items: [
          { id: 'rep-bva', label: 'Budget vs Actual', href: '/reports/budget-vs-actual', description: 'Plan variance by segment.' },
          { id: 'rep-builder', label: 'Report Builder', href: '/reports/builder', description: 'Design and save custom layouts.' },
        ],
      },
    ],
  },
  {
    id: 'company',
    label: 'Company',
    icon: 'Building2',
    href: '/company',
    description: 'Entities, dimensions, departments, and reference structure.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/company', '/multi-entity'],
    groups: [
      {
        id: 'company-structure',
        label: 'Structure',
        items: [
          { id: 'company-home', label: 'Company Overview', href: '/company', description: 'Entity and shared-dimension overview.' },
          { id: 'company-entities', label: 'Entities', href: '/company/entities', description: 'Entity hierarchy and controls.' },
          { id: 'company-dimensions', label: 'Dimensions', href: '/company/dimensions', description: 'Trackable operational dimensions.' },
          { id: 'company-departments', label: 'Departments', href: '/company/departments', description: 'Department ownership and rollup.' },
        ],
      },
      {
        id: 'company-admin',
        label: 'Reference Data',
        items: [
          { id: 'company-locations', label: 'Locations', href: '/company/locations', description: 'Location and jurisdiction setup.' },
          { id: 'company-employees', label: 'Employees', href: '/company/employees', description: 'Approvers and accounting staff.' },
          { id: 'company-multi-entity', label: 'Multi-Entity', href: '/multi-entity', description: 'Cross-entity operations and analysis.' },
        ],
      },
    ],
  },
  {
    id: 'projects',
    label: 'Projects',
    icon: 'FolderKanban',
    href: '/projects',
    description: 'Project-driven tracking and operational cost context.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/projects'],
    groups: [
      {
        id: 'projects-manage',
        label: 'Projects',
        items: [
          { id: 'projects-home', label: 'Projects', href: '/projects', description: 'Track budgets, spend, and delivery status.' },
        ],
      },
    ],
  },
  {
    id: 'purchasing',
    label: 'Purchasing',
    icon: 'ShoppingCart',
    href: '/purchasing',
    description: 'Procurement operations and order intake.',
    roles: ['accountant', 'ap_specialist', 'controller', 'admin'],
    matchers: ['/purchasing'],
    groups: [
      {
        id: 'purchasing-flow',
        label: 'Purchasing',
        items: [
          { id: 'purchasing-home', label: 'Purchase Orders', href: '/purchasing', description: 'Review purchasing activity and order flow.' },
        ],
      },
    ],
  },
  {
    id: 'order-management',
    label: 'Order Mgmt',
    icon: 'Package',
    href: '/order-management',
    description: 'Sales order flow and downstream fulfillment context.',
    roles: ['ar_specialist', 'controller', 'cfo', 'admin'],
    matchers: ['/order-management'],
    groups: [
      {
        id: 'orders-flow',
        label: 'Orders',
        items: [
          { id: 'orders-home', label: 'Sales Orders', href: '/order-management', description: 'Open order activity and customer flow.' },
        ],
      },
    ],
  },
  {
    id: 'admin',
    label: 'Admin',
    icon: 'ShieldCheck',
    href: '/admin',
    description: 'Users, workflows, keys, integrations, and controls.',
    roles: ['controller', 'cfo', 'admin'],
    matchers: ['/admin'],
    groups: [
      {
        id: 'admin-governance',
        label: 'Governance',
        items: [
          { id: 'admin-users', label: 'Users', href: '/admin/users', description: 'User access and role assignment.' },
          { id: 'admin-workflows', label: 'Workflows', href: '/admin/workflows', description: 'Approval flow and routing design.' },
          { id: 'admin-audit', label: 'Audit', href: '/admin/audit', description: 'Auditability and admin oversight.' },
          { id: 'admin-notifications', label: 'Notifications', href: '/admin/notifications', description: 'Alert channels and dispatch rules.' },
        ],
      },
      {
        id: 'admin-platform',
        label: 'Platform',
        items: [
          { id: 'admin-integrations', label: 'Integrations', href: '/admin/integrations', description: 'Connected systems and sync state.' },
          { id: 'admin-api-keys', label: 'API Keys', href: '/admin/api-keys', description: 'Developer credentials and access.' },
          { id: 'admin-custom-fields', label: 'Custom Fields', href: '/admin/custom-fields', description: 'Extend record metadata.' },
        ],
      },
    ],
  },
  {
    id: 'dashboards',
    label: 'Dashboards',
    icon: 'PanelTop',
    href: '/dashboards',
    description: 'Role-shaped dashboard launch point.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/dashboards'],
    status: 'available',
  },
  {
    id: 'budgets-forecasting',
    label: 'Budgets',
    icon: 'Calculator',
    href: '/budgets-forecasting',
    description: 'Budgeting, forecasts, and scenario planning.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/budgets-forecasting'],
    status: 'available',
  },
  {
    id: 'fixed-assets',
    label: 'Fixed Assets',
    icon: 'Factory',
    href: '/fixed-assets',
    description: 'Asset lifecycle, capitalization, and depreciation.',
    roles: ['accountant', 'controller', 'admin'],
    matchers: ['/fixed-assets'],
    status: 'available',
  },
  {
    id: 'contracts-revenue',
    label: 'Contracts',
    icon: 'FileSpreadsheet',
    href: '/contracts-revenue',
    description: 'Contract schedules and revenue operations.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/contracts-revenue'],
    status: 'available',
  },
  {
    id: 'workflows-automation',
    label: 'Automation',
    icon: 'Workflow',
    href: '/workflows-automation',
    description: 'Workflow orchestration and operational automation.',
    roles: ['controller', 'admin'],
    matchers: ['/workflows-automation'],
    status: 'available',
  },
  {
    id: 'integrations',
    label: 'Integrations',
    icon: 'PlugZap',
    href: '/integrations',
    description: 'Connected systems and sync topology.',
    roles: ['controller', 'admin'],
    matchers: ['/integrations'],
    status: 'available',
  },
  {
    id: 'api-developer',
    label: 'Developer',
    icon: 'Code2',
    href: '/api-developer',
    description: 'API surface, keys, and developer tooling.',
    roles: ['admin'],
    matchers: ['/api-developer'],
    status: 'available',
  },
  {
    id: 'ai',
    label: 'AI',
    icon: 'Sparkles',
    href: '/ai',
    description: 'AI copilots, recommendations, and assisted workflows.',
    roles: ['accountant', 'controller', 'cfo', 'admin'],
    matchers: ['/ai'],
    status: 'available',
  },
  {
    id: 'event-monitoring',
    label: 'Events',
    icon: 'ActivitySquare',
    href: '/event-monitoring',
    description: 'Real-time monitoring and operational event streams.',
    roles: ['controller', 'admin'],
    matchers: ['/event-monitoring'],
    status: 'available',
  },
  {
    id: 'rule-engine',
    label: 'Rules',
    icon: 'Scale',
    href: '/rule-engine',
    description: 'Posting, routing, and exception rules.',
    roles: ['controller', 'admin'],
    matchers: ['/rule-engine'],
    status: 'available',
  },
  {
    id: 'exports-sharing',
    label: 'Exports',
    icon: 'Share2',
    href: '/exports-sharing',
    description: 'Distribution, exports, and sharing controls.',
    roles: allPrimaryRoles,
    matchers: ['/exports-sharing'],
    status: 'available',
  },
]

export const roleShellConfigs: RoleShellConfig[] = [
  {
    roleId: 'accountant',
    moduleIds: ['home', 'work-queue', 'general-ledger', 'accounts-payable', 'accounts-receivable', 'cash-management', 'budgets-forecasting', 'fixed-assets', 'contracts-revenue', 'reports', 'dashboards', 'ai', 'exports-sharing', 'company'],
    sidebarSectionIds: ['accountant-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'create', 'reports'],
    homeLabel: 'Accounting Home',
  },
  {
    roleId: 'ap_specialist',
    moduleIds: ['home', 'accounts-payable', 'cash-management', 'work-queue', 'reports', 'company'],
    sidebarSectionIds: ['ap-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'create', 'reports'],
    homeLabel: 'AP Home',
  },
  {
    roleId: 'ar_specialist',
    moduleIds: ['home', 'accounts-receivable', 'cash-management', 'work-queue', 'reports', 'order-management'],
    sidebarSectionIds: ['ar-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'create', 'reports'],
    homeLabel: 'AR Home',
  },
  {
    roleId: 'controller',
    moduleIds: ['home', 'general-ledger', 'cash-management', 'budgets-forecasting', 'fixed-assets', 'contracts-revenue', 'reports', 'dashboards', 'company', 'work-queue', 'admin', 'integrations', 'event-monitoring', 'rule-engine', 'workflows-automation', 'exports-sharing', 'ai'],
    sidebarSectionIds: ['controller-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'create', 'reports', 'admin'],
    homeLabel: 'Controller Home',
  },
  {
    roleId: 'cfo',
    moduleIds: ['home', 'dashboards', 'reports', 'cash-management', 'budgets-forecasting', 'contracts-revenue', 'company', 'ai', 'exports-sharing'],
    sidebarSectionIds: ['executive-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'reports'],
    homeLabel: 'CFO Home',
  },
  {
    roleId: 'admin',
    moduleIds: ['home', 'budgets-forecasting', 'fixed-assets', 'contracts-revenue', 'admin', 'integrations', 'api-developer', 'event-monitoring', 'rule-engine', 'workflows-automation', 'exports-sharing', 'dashboards', 'ai', 'company'],
    sidebarSectionIds: ['admin-core', 'monitoring', 'workspace-admin'],
    commandGroupIds: ['priority-actions', 'navigate', 'admin'],
    homeLabel: 'Admin Home',
  },
]

export const shellSidebarSections: ShellSidebarSection[] = [
  {
    id: 'accountant-core',
    label: 'Accounting',
    roles: ['accountant'],
    items: [
      { id: 'sb-accounting-home', label: 'Accounting Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'], },
      { id: 'sb-work-queue', label: 'Work Queue', href: '/work-queue', icon: 'Inbox', moduleId: 'work-queue', countKey: 'tasks', matchers: ['/work-queue'] },
      { id: 'sb-approvals', label: 'Approvals', href: '/approvals', icon: 'BadgeCheck', moduleId: 'work-queue', matchers: ['/approvals'] },
      { id: 'sb-reconciliation', label: 'Reconciliation', href: '/cash-management/reconciliation', icon: 'ArrowLeftRight', moduleId: 'cash-management', matchers: ['/cash-management/reconciliation'] },
      { id: 'sb-journals', label: 'Journals', href: '/general-ledger/journal-entries', icon: 'BookText', moduleId: 'general-ledger', matchers: ['/general-ledger/journal-entries'] },
      { id: 'sb-budgets', label: 'Budgets', href: '/budgets-forecasting', icon: 'Calculator', moduleId: 'budgets-forecasting', matchers: ['/budgets-forecasting'] },
      { id: 'sb-assets', label: 'Fixed Assets', href: '/fixed-assets', icon: 'Factory', moduleId: 'fixed-assets', matchers: ['/fixed-assets'] },
      { id: 'sb-contracts', label: 'Contracts', href: '/contracts-revenue', icon: 'FileSpreadsheet', moduleId: 'contracts-revenue', matchers: ['/contracts-revenue'] },
      { id: 'sb-close', label: 'Close Tasks', href: '/tasks', icon: 'CheckSquare', moduleId: 'work-queue', matchers: ['/tasks'] },
    ],
  },
  {
    id: 'ap-core',
    label: 'Payables',
    roles: ['ap_specialist'],
    items: [
      { id: 'sb-ap-home', label: 'AP Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'] },
      { id: 'sb-ap-bills', label: 'Bills', href: '/accounts-payable/bills', icon: 'ReceiptText', moduleId: 'accounts-payable', matchers: ['/accounts-payable/bills'] },
      { id: 'sb-ap-approvals', label: 'Approvals', href: '/accounts-payable/approvals', icon: 'BadgeCheck', moduleId: 'accounts-payable', matchers: ['/accounts-payable/approvals'] },
      { id: 'sb-ap-payments', label: 'Payments', href: '/accounts-payable/payments', icon: 'Wallet', moduleId: 'accounts-payable', matchers: ['/accounts-payable/payments'] },
      { id: 'sb-ap-vendors', label: 'Vendors', href: '/accounts-payable/vendors', icon: 'Building2', moduleId: 'accounts-payable', matchers: ['/accounts-payable/vendors'] },
      { id: 'sb-ap-queue', label: 'Shared Queue', href: '/work-queue', icon: 'Inbox', moduleId: 'work-queue', countKey: 'tasks', matchers: ['/work-queue'] },
    ],
  },
  {
    id: 'ar-core',
    label: 'Receivables',
    roles: ['ar_specialist'],
    items: [
      { id: 'sb-ar-home', label: 'AR Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'] },
      { id: 'sb-ar-invoices', label: 'Invoices', href: '/accounts-receivable/invoices', icon: 'FileText', moduleId: 'accounts-receivable', matchers: ['/accounts-receivable/invoices'] },
      { id: 'sb-ar-collections', label: 'Collections', href: '/accounts-receivable/collections', icon: 'PhoneCall', moduleId: 'accounts-receivable', matchers: ['/accounts-receivable/collections'] },
      { id: 'sb-ar-receipts', label: 'Receipts', href: '/accounts-receivable/receipts', icon: 'Wallet', moduleId: 'accounts-receivable', matchers: ['/accounts-receivable/receipts'] },
      { id: 'sb-ar-customers', label: 'Customers', href: '/accounts-receivable/customers', icon: 'Users', moduleId: 'accounts-receivable', matchers: ['/accounts-receivable/customers'] },
      { id: 'sb-ar-queue', label: 'Shared Queue', href: '/work-queue', icon: 'Inbox', moduleId: 'work-queue', countKey: 'tasks', matchers: ['/work-queue'] },
    ],
  },
  {
    id: 'controller-core',
    label: 'Controls',
    roles: ['controller'],
    items: [
      { id: 'sb-controller-home', label: 'Controller Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'] },
      { id: 'sb-controller-tb', label: 'Trial Balance', href: '/general-ledger/reports/trial-balance', icon: 'Scale', moduleId: 'general-ledger', matchers: ['/general-ledger/reports/trial-balance'] },
      { id: 'sb-controller-close', label: 'Close Queue', href: '/work-queue', icon: 'Inbox', moduleId: 'work-queue', countKey: 'tasks', matchers: ['/work-queue'] },
      { id: 'sb-controller-recon', label: 'Reconciliation', href: '/cash-management/reconciliation', icon: 'ArrowLeftRight', moduleId: 'cash-management', matchers: ['/cash-management/reconciliation'] },
      { id: 'sb-controller-reports', label: 'Report Library', href: '/reports', icon: 'LineChart', moduleId: 'reports', matchers: ['/reports'] },
      { id: 'sb-controller-admin', label: 'Admin', href: '/admin', icon: 'ShieldCheck', moduleId: 'admin', matchers: ['/admin'] },
    ],
  },
  {
    id: 'executive-core',
    label: 'Executive',
    roles: ['cfo'],
    items: [
      { id: 'sb-cfo-home', label: 'CFO Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'] },
      { id: 'sb-cfo-dashboards', label: 'Dashboards', href: '/dashboards', icon: 'PanelTop', moduleId: 'dashboards', matchers: ['/dashboards'] },
      { id: 'sb-cfo-pnl', label: 'Income Statement', href: '/reports/income-statement', icon: 'LineChart', moduleId: 'reports', matchers: ['/reports/income-statement'] },
      { id: 'sb-cfo-cash', label: 'Cash Position', href: '/cash-management', icon: 'Landmark', moduleId: 'cash-management', matchers: ['/cash-management'] },
      { id: 'sb-cfo-budget', label: 'Budgeting', href: '/budgets-forecasting', icon: 'Calculator', moduleId: 'budgets-forecasting', matchers: ['/budgets-forecasting'] },
      { id: 'sb-cfo-ai', label: 'AI Insights', href: '/ai', icon: 'Sparkles', moduleId: 'ai', matchers: ['/ai'] },
    ],
  },
  {
    id: 'admin-core',
    label: 'Platform',
    roles: ['admin'],
    items: [
      { id: 'sb-admin-home', label: 'Admin Home', href: '/', icon: 'House', moduleId: 'home', matchers: ['/'] },
      { id: 'sb-admin-users', label: 'Users', href: '/admin/users', icon: 'Users', moduleId: 'admin', matchers: ['/admin/users'] },
      { id: 'sb-admin-workflows', label: 'Workflows', href: '/admin/workflows', icon: 'Workflow', moduleId: 'admin', matchers: ['/admin/workflows'] },
      { id: 'sb-admin-integrations', label: 'Integrations', href: '/integrations', icon: 'PlugZap', moduleId: 'integrations', matchers: ['/integrations', '/admin/integrations'] },
      { id: 'sb-admin-events', label: 'Event Monitoring', href: '/event-monitoring', icon: 'ActivitySquare', moduleId: 'event-monitoring', matchers: ['/event-monitoring'] },
      { id: 'sb-admin-rules', label: 'Rules', href: '/rule-engine', icon: 'Scale', moduleId: 'rule-engine', matchers: ['/rule-engine'] },
    ],
  },
  {
    id: 'monitoring',
    label: 'Monitor',
    roles: allPrimaryRoles,
    items: [
      { id: 'sb-notifications', label: 'Notifications', href: '/notifications', icon: 'Bell', moduleId: 'work-queue', countKey: 'notifications', matchers: ['/notifications'] },
      { id: 'sb-activity', label: 'Activity', href: '/activity', icon: 'Activity', moduleId: 'work-queue', matchers: ['/activity'] },
      { id: 'sb-favorites', label: 'Favorites', href: '/favorites', icon: 'Star', moduleId: 'work-queue', matchers: ['/favorites'] },
    ],
  },
  {
    id: 'workspace-admin',
    label: 'Workspace',
    roles: allPrimaryRoles,
    items: [
      { id: 'sb-company', label: 'Company', href: '/company', icon: 'Building2', moduleId: 'company', matchers: ['/company'] },
      { id: 'sb-projects', label: 'Projects', href: '/projects', icon: 'FolderKanban', moduleId: 'projects', matchers: ['/projects'] },
      { id: 'sb-multi-entity', label: 'Multi-Entity', href: '/multi-entity', icon: 'Layers3', moduleId: 'company', matchers: ['/multi-entity'] },
      { id: 'sb-settings', label: 'Settings', href: '/settings', icon: 'Settings2', moduleId: 'admin', matchers: ['/settings'] },
    ],
  },
]

export const shellCommandGroups: ShellCommandGroup[] = [
  {
    id: 'priority-actions',
    label: 'Priority',
    roles: allPrimaryRoles,
    items: [
      { id: 'cmd-work-queue', label: 'Open Work Queue', href: '/work-queue', icon: 'Inbox', section: 'priority', roles: operatorRoles, keywords: ['queue', 'exceptions', 'tasks'] },
      { id: 'cmd-approvals', label: 'Review Approvals', href: '/approvals', icon: 'BadgeCheck', section: 'priority', roles: operatorRoles, keywords: ['approve', 'review'] },
      { id: 'cmd-reconcile', label: 'Open Reconciliation', href: '/cash-management/reconciliation', icon: 'ArrowLeftRight', section: 'priority', roles: ['accountant', 'controller'], keywords: ['recon', 'cash'] },
      { id: 'cmd-dashboards', label: 'Open Dashboards', href: '/dashboards', icon: 'PanelTop', section: 'priority', roles: ['accountant', 'cfo', 'controller', 'admin'], keywords: ['executive', 'kpi'] },
      { id: 'cmd-users', label: 'Manage Users', href: '/admin/users', icon: 'Users', section: 'priority', roles: ['admin'], keywords: ['access', 'roles'] },
    ],
  },
  {
    id: 'navigate',
    label: 'Navigate',
    roles: allPrimaryRoles,
    items: [
      { id: 'cmd-home', label: 'Role Home', href: '/', icon: 'House', section: 'navigate', roles: allPrimaryRoles, keywords: ['home'] },
      { id: 'cmd-gl', label: 'General Ledger', href: '/general-ledger', icon: 'BookOpenText', section: 'navigate', roles: ['accountant', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-ap', label: 'Accounts Payable', href: '/accounts-payable', icon: 'ReceiptText', section: 'navigate', roles: ['accountant', 'ap_specialist', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-ar', label: 'Accounts Receivable', href: '/accounts-receivable', icon: 'WalletCards', section: 'navigate', roles: ['accountant', 'ar_specialist', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-cash', label: 'Cash Management', href: '/cash-management', icon: 'Landmark', section: 'navigate', roles: allPrimaryRoles },
      { id: 'cmd-reports', label: 'Report Library', href: '/reports', icon: 'LineChart', section: 'navigate', roles: allPrimaryRoles },
      { id: 'cmd-dashboards-nav', label: 'Dashboards', href: '/dashboards', icon: 'PanelTop', section: 'navigate', roles: ['accountant', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-ai-nav', label: 'AI Workspace', href: '/ai', icon: 'Sparkles', section: 'navigate', roles: ['accountant', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-exports', label: 'Exports & Sharing', href: '/exports-sharing', icon: 'Share2', section: 'navigate', roles: allPrimaryRoles },
      { id: 'cmd-integrations-nav', label: 'Integrations', href: '/integrations', icon: 'PlugZap', section: 'navigate', roles: ['controller', 'admin'] },
      { id: 'cmd-events-nav', label: 'Event Monitoring', href: '/event-monitoring', icon: 'ActivitySquare', section: 'navigate', roles: ['controller', 'admin'] },
      { id: 'cmd-rules-nav', label: 'Rule Engine', href: '/rule-engine', icon: 'Scale', section: 'navigate', roles: ['controller', 'admin'] },
      { id: 'cmd-company', label: 'Company', href: '/company', icon: 'Building2', section: 'navigate', roles: ['accountant', 'controller', 'cfo', 'admin'] },
      { id: 'cmd-projects', label: 'Projects', href: '/projects', icon: 'FolderKanban', section: 'navigate', roles: ['accountant', 'controller', 'cfo', 'admin'] },
    ],
  },
  {
    id: 'create',
    label: 'Create',
    roles: operatorRoles,
    items: [
      { id: 'cmd-new-journal', label: 'New Journal Entry', href: '/general-ledger/journal-entries', icon: 'Plus', section: 'create', roles: ['accountant', 'controller'] },
      { id: 'cmd-new-bill', label: 'New Bill', href: '/accounts-payable/bills', icon: 'Plus', section: 'create', roles: ['accountant', 'ap_specialist', 'controller'] },
      { id: 'cmd-new-invoice', label: 'New Invoice', href: '/accounts-receivable/invoices', icon: 'Plus', section: 'create', roles: ['accountant', 'ar_specialist', 'controller'] },
      { id: 'cmd-transfer', label: 'Create Transfer', href: '/cash-management/transfers', icon: 'Plus', section: 'create', roles: ['accountant', 'controller'] },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    roles: allPrimaryRoles,
    items: [
      { id: 'cmd-pnl', label: 'Income Statement', href: '/reports/income-statement', icon: 'LineChart', section: 'reports', roles: allPrimaryRoles, keywords: ['pnl', 'income'] },
      { id: 'cmd-balance-sheet', label: 'Balance Sheet', href: '/reports/balance-sheet', icon: 'Scale', section: 'reports', roles: allPrimaryRoles },
      { id: 'cmd-cash-flow', label: 'Cash Flow', href: '/reports/cash-flow', icon: 'Landmark', section: 'reports', roles: allPrimaryRoles },
      { id: 'cmd-budget-vs-actual', label: 'Budget vs Actual', href: '/reports/budget-vs-actual', icon: 'Calculator', section: 'reports', roles: ['controller', 'cfo', 'admin'] },
      { id: 'cmd-builder', label: 'Report Builder', href: '/reports/builder', icon: 'FileSpreadsheet', section: 'reports', roles: ['controller', 'cfo', 'admin'] },
    ],
  },
  {
    id: 'admin',
    label: 'Admin',
    roles: ['controller', 'admin'],
    items: [
      { id: 'cmd-admin-users', label: 'Users', href: '/admin/users', icon: 'Users', section: 'admin', roles: ['controller', 'admin'] },
      { id: 'cmd-admin-workflows', label: 'Workflows', href: '/admin/workflows', icon: 'Workflow', section: 'admin', roles: ['controller', 'admin'] },
      { id: 'cmd-integrations', label: 'Integrations', href: '/integrations', icon: 'PlugZap', section: 'admin', roles: ['controller', 'admin'] },
      { id: 'cmd-api', label: 'API / Developer', href: '/api-developer', icon: 'Code2', section: 'admin', roles: ['admin'] },
    ],
  },
]

export const shellBreadcrumbDefinitions: ShellBreadcrumbDefinition[] = [
  { path: '/work-queue', label: 'Work Queue', moduleId: 'work-queue', href: '/work-queue' },
  { path: '/activity', label: 'Activity', moduleId: 'work-queue', href: '/activity' },
  { path: '/approvals', label: 'Approvals', moduleId: 'work-queue', href: '/approvals' },
  { path: '/favorites', label: 'Favorites', moduleId: 'work-queue', href: '/favorites' },
  { path: '/notifications', label: 'Notifications', moduleId: 'work-queue', href: '/notifications' },
  { path: '/tasks', label: 'Tasks', moduleId: 'work-queue', href: '/tasks' },
  { path: '/general-ledger', label: 'General Ledger', moduleId: 'general-ledger', href: '/general-ledger' },
  { path: '/general-ledger/accounting-periods', label: 'Accounting Periods', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/accounting-periods' },
  { path: '/general-ledger/allocations', label: 'Allocations', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/allocations' },
  { path: '/general-ledger/audit-trail', label: 'Audit Trail', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/audit-trail' },
  { path: '/general-ledger/chart-of-accounts', label: 'Chart of Accounts', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/chart-of-accounts' },
  { path: '/general-ledger/journal-entries', label: 'Journal Entries', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/journal-entries' },
  { path: '/general-ledger/recurring-journals', label: 'Recurring Journals', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/recurring-journals' },
  { path: '/general-ledger/reports/trial-balance', label: 'Trial Balance', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/reports/trial-balance' },
  { path: '/general-ledger/close-management', label: 'Close Management', parentPath: '/general-ledger', moduleId: 'general-ledger', href: '/general-ledger/close-management' },
  { path: '/general-ledger/chart-of-accounts/[id]', label: 'Account Detail', parentPath: '/general-ledger/chart-of-accounts', moduleId: 'general-ledger' },
  { path: '/general-ledger/journal-entries/[id]', label: 'Journal Entry Detail', parentPath: '/general-ledger/journal-entries', moduleId: 'general-ledger' },
  { path: '/accounts-payable', label: 'Accounts Payable', moduleId: 'accounts-payable', href: '/accounts-payable' },
  { path: '/accounts-payable/aging', label: 'AP Aging', parentPath: '/accounts-payable', moduleId: 'accounts-payable', href: '/accounts-payable/aging' },
  { path: '/accounts-payable/approvals', label: 'Approvals', parentPath: '/accounts-payable', moduleId: 'accounts-payable', href: '/accounts-payable/approvals' },
  { path: '/accounts-payable/bills', label: 'Bills', parentPath: '/accounts-payable', moduleId: 'accounts-payable', href: '/accounts-payable/bills' },
  { path: '/accounts-payable/payments', label: 'Payments', parentPath: '/accounts-payable', moduleId: 'accounts-payable', href: '/accounts-payable/payments' },
  { path: '/accounts-payable/vendors', label: 'Vendors', parentPath: '/accounts-payable', moduleId: 'accounts-payable', href: '/accounts-payable/vendors' },
  { path: '/accounts-payable/vendors/[id]', label: 'Vendor Detail', parentPath: '/accounts-payable/vendors', moduleId: 'accounts-payable' },
  { path: '/accounts-payable/bills/[id]', label: 'Bill Detail', parentPath: '/accounts-payable/bills', moduleId: 'accounts-payable' },
  { path: '/accounts-receivable', label: 'Accounts Receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable' },
  { path: '/accounts-receivable/aging', label: 'AR Aging', parentPath: '/accounts-receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable/aging' },
  { path: '/accounts-receivable/collections', label: 'Collections', parentPath: '/accounts-receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable/collections' },
  { path: '/accounts-receivable/customers', label: 'Customers', parentPath: '/accounts-receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable/customers' },
  { path: '/accounts-receivable/invoices', label: 'Invoices', parentPath: '/accounts-receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable/invoices' },
  { path: '/accounts-receivable/receipts', label: 'Receipts', parentPath: '/accounts-receivable', moduleId: 'accounts-receivable', href: '/accounts-receivable/receipts' },
  { path: '/accounts-receivable/customers/[id]', label: 'Customer Detail', parentPath: '/accounts-receivable/customers', moduleId: 'accounts-receivable' },
  { path: '/accounts-receivable/invoices/[id]', label: 'Invoice Detail', parentPath: '/accounts-receivable/invoices', moduleId: 'accounts-receivable' },
  { path: '/cash-management', label: 'Cash Management', moduleId: 'cash-management', href: '/cash-management' },
  { path: '/cash-management/accounts', label: 'Bank Accounts', parentPath: '/cash-management', moduleId: 'cash-management', href: '/cash-management/accounts' },
  { path: '/cash-management/card-feed', label: 'Card Feed', parentPath: '/cash-management', moduleId: 'cash-management', href: '/cash-management/card-feed' },
  { path: '/cash-management/reconciliation', label: 'Reconciliation', parentPath: '/cash-management', moduleId: 'cash-management', href: '/cash-management/reconciliation' },
  { path: '/cash-management/transactions', label: 'Transactions', parentPath: '/cash-management', moduleId: 'cash-management', href: '/cash-management/transactions' },
  { path: '/cash-management/transfers', label: 'Transfers', parentPath: '/cash-management', moduleId: 'cash-management', href: '/cash-management/transfers' },
  { path: '/cash-management/accounts/[id]', label: 'Bank Account Detail', parentPath: '/cash-management/accounts', moduleId: 'cash-management' },
  { path: '/documents', label: 'Documents', moduleId: 'work-queue', href: '/documents' },
  { path: '/reports', label: 'Reports', moduleId: 'reports', href: '/reports' },
  { path: '/reports/balance-sheet', label: 'Balance Sheet', parentPath: '/reports', moduleId: 'reports', href: '/reports/balance-sheet' },
  { path: '/reports/budget-vs-actual', label: 'Budget vs Actual', parentPath: '/reports', moduleId: 'reports', href: '/reports/budget-vs-actual' },
  { path: '/reports/builder', label: 'Report Builder', parentPath: '/reports', moduleId: 'reports', href: '/reports/builder' },
  { path: '/reports/cash-flow', label: 'Cash Flow', parentPath: '/reports', moduleId: 'reports', href: '/reports/cash-flow' },
  { path: '/reports/income-statement', label: 'Income Statement', parentPath: '/reports', moduleId: 'reports', href: '/reports/income-statement' },
  { path: '/reports/[id]', label: 'Report Detail', parentPath: '/reports', moduleId: 'reports' },
  { path: '/company', label: 'Company', moduleId: 'company', href: '/company' },
  { path: '/company/departments', label: 'Departments', parentPath: '/company', moduleId: 'company', href: '/company/departments' },
  { path: '/company/dimensions', label: 'Dimensions', parentPath: '/company', moduleId: 'company', href: '/company/dimensions' },
  { path: '/company/employees', label: 'Employees', parentPath: '/company', moduleId: 'company', href: '/company/employees' },
  { path: '/company/entities', label: 'Entities', parentPath: '/company', moduleId: 'company', href: '/company/entities' },
  { path: '/company/locations', label: 'Locations', parentPath: '/company', moduleId: 'company', href: '/company/locations' },
  { path: '/multi-entity', label: 'Multi-Entity', parentPath: '/company', moduleId: 'company', href: '/multi-entity' },
  { path: '/projects', label: 'Projects', moduleId: 'projects', href: '/projects' },
  { path: '/projects/[id]', label: 'Project Detail', parentPath: '/projects', moduleId: 'projects' },
  { path: '/purchasing', label: 'Purchasing', moduleId: 'purchasing', href: '/purchasing' },
  { path: '/purchasing/orders/[id]', label: 'Purchase Order Detail', parentPath: '/purchasing', moduleId: 'purchasing' },
  { path: '/order-management', label: 'Order Management', moduleId: 'order-management', href: '/order-management' },
  { path: '/order-management/orders/[id]', label: 'Sales Order Detail', parentPath: '/order-management', moduleId: 'order-management' },
  { path: '/settings', label: 'Settings', moduleId: 'admin', href: '/settings' },
  { path: '/time-expenses', label: 'Time & Expenses', moduleId: 'work-queue', href: '/time-expenses' },
  { path: '/admin', label: 'Admin', moduleId: 'admin', href: '/admin' },
  { path: '/admin/api-keys', label: 'API Keys', parentPath: '/admin', moduleId: 'admin', href: '/admin/api-keys' },
  { path: '/admin/audit', label: 'Audit', parentPath: '/admin', moduleId: 'admin', href: '/admin/audit' },
  { path: '/admin/custom-fields', label: 'Custom Fields', parentPath: '/admin', moduleId: 'admin', href: '/admin/custom-fields' },
  { path: '/admin/integrations', label: 'Admin Integrations', parentPath: '/admin', moduleId: 'admin', href: '/admin/integrations' },
  { path: '/admin/notifications', label: 'Admin Notifications', parentPath: '/admin', moduleId: 'admin', href: '/admin/notifications' },
  { path: '/admin/users', label: 'Users', parentPath: '/admin', moduleId: 'admin', href: '/admin/users' },
  { path: '/admin/workflows', label: 'Workflows', parentPath: '/admin', moduleId: 'admin', href: '/admin/workflows' },
  { path: '/dashboards', label: 'Dashboards', moduleId: 'dashboards', href: '/dashboards' },
  { path: '/budgets-forecasting', label: 'Budgets & Forecasting', moduleId: 'budgets-forecasting', href: '/budgets-forecasting' },
  { path: '/fixed-assets', label: 'Fixed Assets', moduleId: 'fixed-assets', href: '/fixed-assets' },
  { path: '/fixed-assets/[id]', label: 'Asset Detail', parentPath: '/fixed-assets', moduleId: 'fixed-assets' },
  { path: '/contracts-revenue', label: 'Contracts & Revenue', moduleId: 'contracts-revenue', href: '/contracts-revenue' },
  { path: '/contracts-revenue/[id]', label: 'Contract Detail', parentPath: '/contracts-revenue', moduleId: 'contracts-revenue' },
  { path: '/workflows-automation', label: 'Workflows & Automation', moduleId: 'workflows-automation', href: '/workflows-automation' },
  { path: '/integrations', label: 'Integrations', moduleId: 'integrations', href: '/integrations' },
  { path: '/api-developer', label: 'API / Developer', moduleId: 'api-developer', href: '/api-developer' },
  { path: '/ai', label: 'AI', moduleId: 'ai', href: '/ai' },
  { path: '/event-monitoring', label: 'Event Monitoring', moduleId: 'event-monitoring', href: '/event-monitoring' },
  { path: '/rule-engine', label: 'Rule Engine', moduleId: 'rule-engine', href: '/rule-engine' },
  { path: '/exports-sharing', label: 'Exports & Sharing', moduleId: 'exports-sharing', href: '/exports-sharing' },
]

export const shellStubPages: ShellStubPage[] = [
  {
    path: '/work-queue',
    title: 'Work Queue',
    subtitle: 'Shared accounting inbox for approvals, close tasks, and operational exceptions.',
    moduleId: 'work-queue',
    status: 'available',
    primaryLinks: [
      { id: 'stub-wq-approvals', label: 'Approvals', href: '/approvals', description: 'Review documents awaiting release.' },
      { id: 'stub-wq-tasks', label: 'Task Board', href: '/tasks', description: 'Track assigned work and due dates.' },
      { id: 'stub-wq-reconciliation', label: 'Reconciliation', href: '/cash-management/reconciliation', description: 'Investigate unmatched activity.' },
    ],
    upcoming: ['Queue-specific saved views', 'Bulk close actions', 'Exception drawer workspace'],
    roleIds: operatorRoles,
  },
  {
    path: '/general-ledger',
    title: 'General Ledger',
    subtitle: 'Control postings, periods, and the structure that powers financial reporting.',
    moduleId: 'general-ledger',
    status: 'available',
    primaryLinks: [
      { id: 'stub-gl-journals', label: 'Journal Entries', href: '/general-ledger/journal-entries', description: 'Prepare and review journals.' },
      { id: 'stub-gl-coa', label: 'Chart of Accounts', href: '/general-ledger/chart-of-accounts', description: 'Maintain account structure.' },
      { id: 'stub-gl-tb', label: 'Trial Balance', href: '/general-ledger/reports/trial-balance', description: 'Validate balances before reporting.' },
    ],
    upcoming: ['Close workspace', 'Intercompany controls', 'Journal review drawers'],
    roleIds: ['accountant', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/accounts-payable',
    title: 'Accounts Payable',
    subtitle: 'Run vendor operations with a bill-to-payment control surface.',
    moduleId: 'accounts-payable',
    status: 'available',
    primaryLinks: [
      { id: 'stub-ap-bills', label: 'Bills', href: '/accounts-payable/bills', description: 'Code and route incoming bills.' },
      { id: 'stub-ap-payments', label: 'Payments', href: '/accounts-payable/payments', description: 'Release and track payments.' },
      { id: 'stub-ap-vendors', label: 'Vendors', href: '/accounts-payable/vendors', description: 'Review vendor master data.' },
    ],
    upcoming: ['Invoice capture workspace', 'Payment proposal batches', 'Discount optimization'],
    roleIds: ['accountant', 'ap_specialist', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/accounts-receivable',
    title: 'Accounts Receivable',
    subtitle: 'Manage invoicing, collections, and application of cash.',
    moduleId: 'accounts-receivable',
    status: 'available',
    primaryLinks: [
      { id: 'stub-ar-invoices', label: 'Invoices', href: '/accounts-receivable/invoices', description: 'Issue and monitor invoices.' },
      { id: 'stub-ar-collections', label: 'Collections', href: '/accounts-receivable/collections', description: 'Prioritize overdue balances.' },
      { id: 'stub-ar-receipts', label: 'Receipts', href: '/accounts-receivable/receipts', description: 'Apply incoming cash.' },
    ],
    upcoming: ['Dispute management', 'Promise-to-pay tracking', 'Customer credit controls'],
    roleIds: ['accountant', 'ar_specialist', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/budgets-forecasting',
    title: 'Budgets & Forecasting',
    subtitle: 'Plan scenarios, track variance, and coordinate forecast cycles.',
    moduleId: 'budgets-forecasting',
    status: 'available',
    primaryLinks: [
      { id: 'stub-bf-bva', label: 'Budget vs Actual', href: '/reports/budget-vs-actual', description: 'Analyze current plan variance.' },
      { id: 'stub-bf-reports', label: 'Report Library', href: '/reports', description: 'Start from current reporting outputs.' },
    ],
    upcoming: ['Driver-based forecasting', 'Scenario versions', 'Owner submissions'],
    roleIds: ['accountant', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/fixed-assets',
    title: 'Fixed Assets',
    subtitle: 'Track capitalization, depreciation, and asset lifecycle controls.',
    moduleId: 'fixed-assets',
    status: 'available',
    primaryLinks: [
      { id: 'stub-fa-gl', label: 'General Ledger', href: '/general-ledger', description: 'Use existing GL structure and period control.' },
      { id: 'stub-fa-audit', label: 'Audit Trail', href: '/general-ledger/audit-trail', description: 'Review related accounting history.' },
    ],
    upcoming: ['Asset register', 'Depreciation books', 'Disposal workflow'],
    roleIds: ['accountant', 'controller', 'admin'],
  },
  {
    path: '/contracts-revenue',
    title: 'Contracts & Revenue',
    subtitle: 'Coordinate contract schedules and downstream revenue recognition.',
    moduleId: 'contracts-revenue',
    status: 'available',
    primaryLinks: [
      { id: 'stub-cr-orders', label: 'Order Management', href: '/order-management', description: 'Review upstream sales order activity.' },
      { id: 'stub-cr-reports', label: 'Income Statement', href: '/reports/income-statement', description: 'Check recognized revenue output.' },
    ],
    upcoming: ['Revenue schedules', 'Performance obligations', 'Contract modifications'],
    roleIds: ['accountant', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/dashboards',
    title: 'Dashboards',
    subtitle: 'Launch role-shaped dashboard views without mixing them into the module workspace.',
    moduleId: 'dashboards',
    status: 'available',
    primaryLinks: [
      { id: 'stub-dash-reports', label: 'Reporting', href: '/reports', description: 'Open the reporting library.' },
      { id: 'stub-dash-cash', label: 'Cash Management', href: '/cash-management', description: 'Review liquidity and bank operations.' },
    ],
    upcoming: ['Role presets', 'Entity dashboard packs', 'Pinned executive views'],
    roleIds: ['accountant', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/workflows-automation',
    title: 'Workflows & Automation',
    subtitle: 'Govern approval routing and finance automation from one control surface.',
    moduleId: 'workflows-automation',
    status: 'available',
    primaryLinks: [
      { id: 'stub-wa-admin', label: 'Admin Workflows', href: '/admin/workflows', description: 'Review current workflow configuration.' },
      { id: 'stub-wa-approvals', label: 'Approvals', href: '/approvals', description: 'See live approval workload.' },
    ],
    upcoming: ['Rule designer', 'Escalation policies', 'Automation run history'],
    roleIds: ['controller', 'admin'],
  },
  {
    path: '/integrations',
    title: 'Integrations',
    subtitle: 'Monitor connected systems, sync health, and downstream finance dependencies.',
    moduleId: 'integrations',
    status: 'available',
    primaryLinks: [
      { id: 'stub-int-admin', label: 'Admin Integrations', href: '/admin/integrations', description: 'View existing connected systems.' },
      { id: 'stub-int-events', label: 'Event Monitoring', href: '/event-monitoring', description: 'Track sync and webhook activity.' },
    ],
    upcoming: ['Sync runs', 'Connector catalog', 'Error retry controls'],
    roleIds: ['controller', 'admin'],
  },
  {
    path: '/api-developer',
    title: 'API / Developer Platform',
    subtitle: 'Expose API access, keys, and integration setup for finance tooling.',
    moduleId: 'api-developer',
    status: 'available',
    primaryLinks: [
      { id: 'stub-api-keys', label: 'API Keys', href: '/admin/api-keys', description: 'Manage credentials and access.' },
      { id: 'stub-api-integrations', label: 'Integrations', href: '/integrations', description: 'Review platform connectivity.' },
    ],
    upcoming: ['Webhook endpoints', 'Developer docs', 'Usage visibility'],
    roleIds: ['admin'],
  },
  {
    path: '/ai',
    title: 'AI',
    subtitle: 'Coordinate AI-driven recommendations, copilots, and finance review signals.',
    moduleId: 'ai',
    status: 'available',
    primaryLinks: [
      { id: 'stub-ai-reports', label: 'Reporting', href: '/reports', description: 'Start from the current financial narrative.' },
      { id: 'stub-ai-events', label: 'Event Monitoring', href: '/event-monitoring', description: 'Pair AI recommendations with live events.' },
    ],
    upcoming: ['Exception summaries', 'Narrative variance analysis', 'Suggested workflow actions'],
    roleIds: ['accountant', 'controller', 'cfo', 'admin'],
  },
  {
    path: '/event-monitoring',
    title: 'Event Monitoring',
    subtitle: 'Monitor operational signals, sync runs, and finance-impacting events in real time.',
    moduleId: 'event-monitoring',
    status: 'available',
    primaryLinks: [
      { id: 'stub-events-activity', label: 'Activity', href: '/activity', description: 'See current finance event flow.' },
      { id: 'stub-events-integrations', label: 'Integrations', href: '/integrations', description: 'Review connected system health.' },
    ],
    upcoming: ['Event stream', 'Alert subscriptions', 'Runbook actions'],
    roleIds: ['controller', 'admin'],
  },
  {
    path: '/rule-engine',
    title: 'Rule Engine',
    subtitle: 'Manage accounting rules, routing logic, and exception policies.',
    moduleId: 'rule-engine',
    status: 'available',
    primaryLinks: [
      { id: 'stub-rules-workflows', label: 'Admin Workflows', href: '/admin/workflows', description: 'Start from current routing configuration.' },
      { id: 'stub-rules-audit', label: 'Audit', href: '/admin/audit', description: 'Review control history and changes.' },
    ],
    upcoming: ['Posting rules', 'Threshold routing', 'Exception auto-assignment'],
    roleIds: ['controller', 'admin'],
  },
  {
    path: '/exports-sharing',
    title: 'Exports & Sharing',
    subtitle: 'Control how finance outputs are exported, distributed, and shared across teams.',
    moduleId: 'exports-sharing',
    status: 'available',
    primaryLinks: [
      { id: 'stub-exp-reports', label: 'Report Library', href: '/reports', description: 'Start from saved report outputs.' },
      { id: 'stub-exp-favorites', label: 'Favorites', href: '/favorites', description: 'Review the most-used saved outputs.' },
    ],
    upcoming: ['Distribution lists', 'Scheduled exports', 'Secure share links'],
    roleIds: allPrimaryRoles,
  },
  {
    path: '/admin',
    title: 'Admin',
    subtitle: 'Manage access, workflow governance, and connected platform controls.',
    moduleId: 'admin',
    status: 'available',
    primaryLinks: [
      { id: 'stub-admin-users', label: 'Users', href: '/admin/users', description: 'Assign roles and manage access.' },
      { id: 'stub-admin-workflows', label: 'Workflows', href: '/admin/workflows', description: 'Review finance process routing.' },
      { id: 'stub-admin-integrations', label: 'Integrations', href: '/admin/integrations', description: 'Inspect connected systems.' },
    ],
    upcoming: ['Audit dashboards', 'Role policies', 'Notification governance'],
    roleIds: ['controller', 'cfo', 'admin'],
  },
]
