import type {
  WorkQueueActionDefinition,
  WorkQueueItemStateOverride,
  WorkQueueImportError,
  WorkQueueMissingDocumentIssue,
  WorkQueueSectionDefinition,
} from '@/lib/types'

export const workQueueSections: WorkQueueSectionDefinition[] = [
  {
    id: 'needs_review',
    label: 'Needs Review',
    description: 'Draft journals and operator review work waiting for accounting action.',
    icon: 'CheckSquare',
    columns: ['item', 'reference', 'source', 'department', 'assignee', 'priority', 'dueDate'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    availableActionIds: ['assign', 'assign_to_me', 'mark_reviewed', 'snooze'],
  },
  {
    id: 'approvals',
    label: 'Approvals',
    description: 'Pending approval routing across payables and controllership.',
    icon: 'BadgeCheck',
    columns: ['item', 'reference', 'entity', 'amount', 'assignee', 'priority', 'dueDate'],
    defaultSort: { key: 'priority', direction: 'desc' },
    availableActionIds: ['assign', 'assign_to_me', 'approve', 'send_back', 'snooze'],
  },
  {
    id: 'reconciliation_exceptions',
    label: 'Reconciliation Exceptions',
    description: 'Outstanding breaks, variances, and uncleared bank activity.',
    icon: 'ArrowLeftRight',
    columns: ['item', 'reference', 'entity', 'amount', 'status', 'assignee', 'dueDate'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    availableActionIds: ['assign', 'assign_to_me', 'resolve', 'snooze'],
  },
  {
    id: 'missing_documents',
    label: 'Missing Documents',
    description: 'Support packages and attachments that are still required before close or approval.',
    icon: 'FileText',
    columns: ['item', 'reference', 'source', 'department', 'assignee', 'status', 'dueDate'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    availableActionIds: ['assign', 'assign_to_me', 'request_documents', 'snooze'],
  },
  {
    id: 'import_errors',
    label: 'Import Errors',
    description: 'Feed, import, and mapping failures that need operator intervention.',
    icon: 'ActivitySquare',
    columns: ['item', 'source', 'entity', 'status', 'assignee', 'priority', 'updatedAt'],
    defaultSort: { key: 'updatedAt', direction: 'desc' },
    availableActionIds: ['assign', 'assign_to_me', 'retry_import', 'resolve', 'snooze'],
  },
  {
    id: 'close_tasks',
    label: 'Close Tasks',
    description: 'Period-close tasks and blockers by entity, owner, and phase.',
    icon: 'BookOpenText',
    columns: ['item', 'entity', 'department', 'assignee', 'status', 'priority', 'dueDate'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    availableActionIds: ['assign', 'assign_to_me', 'start_task', 'complete_task', 'snooze'],
  },
  {
    id: 'assigned_to_me',
    label: 'Assigned to Me',
    description: 'Your actionable queue across approvals, close, review, and exceptions.',
    icon: 'Inbox',
    columns: ['item', 'source', 'entity', 'status', 'priority', 'dueDate', 'updatedAt'],
    defaultSort: { key: 'dueDate', direction: 'asc' },
    availableActionIds: ['assign', 'assign_to_me', 'snooze'],
  },
]

export const workQueueActionDefinitions: WorkQueueActionDefinition[] = [
  {
    id: 'assign',
    label: 'Assign',
    description: 'Route the selected work to another owner.',
    icon: 'Users',
    tone: 'neutral',
  },
  {
    id: 'assign_to_me',
    label: 'Assign To Me',
    description: 'Take ownership of the selected work immediately.',
    icon: 'Inbox',
    tone: 'accent',
  },
  {
    id: 'mark_reviewed',
    label: 'Mark Reviewed',
    description: 'Complete review and remove the item from the queue.',
    icon: 'CheckSquare',
    tone: 'positive',
  },
  {
    id: 'resolve',
    label: 'Resolve',
    description: 'Mark the exception as resolved and remove it from the active queue.',
    icon: 'BadgeCheck',
    tone: 'positive',
  },
  {
    id: 'request_documents',
    label: 'Request Documents',
    description: 'Send a document request and keep the item tracked in the workspace.',
    icon: 'FileText',
    tone: 'warning',
  },
  {
    id: 'snooze',
    label: 'Snooze',
    description: 'Temporarily defer the work and resurface it later.',
    icon: 'Activity',
    tone: 'warning',
  },
  {
    id: 'approve',
    label: 'Approve',
    description: 'Approve the routed item and remove it from the approval queue.',
    icon: 'BadgeCheck',
    tone: 'positive',
  },
  {
    id: 'send_back',
    label: 'Send Back',
    description: 'Return the item for correction or additional support.',
    icon: 'ArrowLeftRight',
    tone: 'critical',
  },
  {
    id: 'retry_import',
    label: 'Retry Import',
    description: 'Retry the import after fixing the underlying issue.',
    icon: 'RefreshCcw',
    tone: 'accent',
  },
  {
    id: 'start_task',
    label: 'Start Task',
    description: 'Move the close task into active execution.',
    icon: 'Play',
    tone: 'accent',
  },
  {
    id: 'complete_task',
    label: 'Complete Task',
    description: 'Mark the task complete and remove it from the close queue.',
    icon: 'BadgeCheck',
    tone: 'positive',
  },
]

export const workQueueMissingDocumentIssues: WorkQueueMissingDocumentIssue[] = [
  {
    id: 'wq-missing-doc-1',
    title: 'Payroll accrual support is missing the payroll register',
    description: 'Controller sign-off is waiting on the payroll register and approval summary for JE-2026-1003.',
    entityId: 'e2',
    entityName: 'Northstar Manufacturing West',
    departmentId: 'd-ops',
    departmentName: 'Operations',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    sourceEntityType: 'journal_entry',
    sourceEntityId: 'je-1003',
    sourceLabel: 'Journal Entry',
    reference: 'JE-2026-1003',
    amount: 86000,
    currency: 'USD',
    requiredDocuments: ['Payroll register', 'Approver sign-off summary'],
    status: 'new',
    priority: 'high',
    dueDate: new Date('2026-04-04T15:00:00'),
    createdAt: new Date('2026-04-03T16:40:00'),
    updatedAt: new Date('2026-04-04T08:12:00'),
  },
  {
    id: 'wq-missing-doc-2',
    title: 'SkyGrid vendor packet is incomplete',
    description: 'AP cannot release BILL-7603 without the renewal order form and vendor contact confirmation.',
    entityId: 'e1',
    entityName: 'Northstar Holdings',
    departmentId: 'd-it',
    departmentName: 'IT',
    projectId: 'p-erp',
    projectName: 'ERP Data Migration',
    assigneeId: 'u3',
    assigneeName: 'Lena Garcia',
    sourceEntityType: 'bill',
    sourceEntityId: 'bill-7603',
    sourceLabel: 'Bill',
    reference: 'BILL-7603',
    amount: 26400,
    currency: 'USD',
    requiredDocuments: ['Renewal order form', 'Updated vendor contact sheet'],
    status: 'requested',
    priority: 'medium',
    dueDate: new Date('2026-04-05T12:00:00'),
    createdAt: new Date('2026-04-03T10:10:00'),
    updatedAt: new Date('2026-04-04T08:05:00'),
  },
  {
    id: 'wq-missing-doc-3',
    title: 'Berlin settlement support needs counterparty confirmation',
    description: 'The EU intercompany elimination task is blocked until the counterparty settlement backup is uploaded.',
    entityId: 'e3',
    entityName: 'Northstar Europe',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-eu',
    projectName: 'EU Shared Services',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    sourceEntityType: 'close_task',
    sourceEntityId: 'close-5',
    sourceLabel: 'Close Task',
    reference: 'EU-ELIM',
    requiredDocuments: ['Counterparty settlement confirmation', 'Intercompany support memo'],
    status: 'new',
    priority: 'critical',
    dueDate: new Date('2026-04-06T10:00:00'),
    createdAt: new Date('2026-04-04T07:15:00'),
    updatedAt: new Date('2026-04-04T07:25:00'),
  },
]

export const workQueueImportErrors: WorkQueueImportError[] = [
  {
    id: 'wq-import-error-1',
    title: 'Bank feed file rejected for EU operating account',
    description: 'The latest Deutsche Bank feed failed schema validation because the transaction date column is missing.',
    entityId: 'e3',
    entityName: 'Northstar Europe',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    sourceSystem: 'Deutsche Bank',
    importType: 'bank_feed',
    errorCode: 'BANK_SCHEMA_MISSING_DATE',
    affectedRecords: 37,
    sourceLabel: 'Bank Feed',
    sourceEntityType: 'bank_account',
    sourceEntityId: 'ba-eu',
    reference: 'EU-FEED-2026-04-04',
    status: 'error',
    priority: 'critical',
    dueDate: new Date('2026-04-04T14:00:00'),
    createdAt: new Date('2026-04-04T06:20:00'),
    updatedAt: new Date('2026-04-04T06:20:00'),
  },
  {
    id: 'wq-import-error-2',
    title: 'Vendor master import contains duplicate tax IDs',
    description: 'The onboarding file for two new logistics vendors contains duplicate tax ID values and was held for review.',
    entityId: 'e1',
    entityName: 'Northstar Holdings',
    departmentId: 'd-fin',
    departmentName: 'Finance',
    projectId: 'p-erp',
    projectName: 'ERP Data Migration',
    assigneeId: 'u3',
    assigneeName: 'Lena Garcia',
    sourceSystem: 'Vendor Onboarding CSV',
    importType: 'vendor_import',
    errorCode: 'DUPLICATE_TAX_ID',
    affectedRecords: 2,
    sourceLabel: 'Vendor Import',
    reference: 'VEND-ONBOARD-0404',
    status: 'error',
    priority: 'high',
    dueDate: new Date('2026-04-04T16:30:00'),
    createdAt: new Date('2026-04-04T07:40:00'),
    updatedAt: new Date('2026-04-04T07:45:00'),
  },
]

export const workQueueItemOverrides: WorkQueueItemStateOverride[] = [
  {
    itemId: 'wq-journal-review-je-1003',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    dueDate: new Date('2026-04-04T11:30:00'),
    priority: 'high',
    status: 'needs_review',
    updatedAt: new Date('2026-04-04T08:30:00'),
  },
  {
    itemId: 'wq-journal-review-je-1005',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    dueDate: new Date('2026-04-05T13:00:00'),
    priority: 'medium',
    status: 'needs_review',
    updatedAt: new Date('2026-04-04T08:25:00'),
  },
  {
    itemId: 'wq-approval-ap-2001',
    assigneeId: 'u2',
    assigneeName: 'Miles Chen',
    dueDate: new Date('2026-04-04T17:00:00'),
    priority: 'high',
    status: 'pending_approval',
    updatedAt: new Date('2026-04-04T08:18:00'),
  },
  {
    itemId: 'wq-approval-ap-3001',
    assigneeId: 'u2',
    assigneeName: 'Miles Chen',
    dueDate: new Date('2026-04-05T10:00:00'),
    priority: 'critical',
    status: 'pending_approval',
    updatedAt: new Date('2026-04-04T08:00:00'),
  },
  {
    itemId: 'wq-reconciliation-rec-3',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    dueDate: new Date('2026-04-04T12:00:00'),
    priority: 'high',
    status: 'needs_review',
    updatedAt: new Date('2026-04-04T08:35:00'),
  },
  {
    itemId: 'wq-reconciliation-rec-4',
    assigneeId: 'u1',
    assigneeName: 'Ava Mitchell',
    dueDate: new Date('2026-04-05T09:30:00'),
    priority: 'critical',
    status: 'blocked',
    updatedAt: new Date('2026-04-04T08:40:00'),
  },
]
